/* eslint-disable */
// @ts-nocheck
/**
 * TypeScript declaration merging to add Nimbus's custom recipes to Chakra's type system.
 *
 * ⚠️  AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Generated by: scripts/generate-chakra-augmentation.mjs
 * Source: generated-types/recipes.gen.d.ts
 *
 * This file augments @chakra-ui/react's ConfigSlotRecipes and ConfigRecipes interfaces
 * with Nimbus-specific recipes so that SlotRecipeProps and RecipeProps lookups work correctly.
 *
 * Without this augmentation, types like `SlotRecipeProps<"nimbusDrawer">["placement"]`
 * would resolve to `never` (widened to `any`), losing all type safety.
 *
 * How it works:
 * - TypeScript's declaration merging allows us to extend third-party module interfaces
 * - When consumers import from @commercetools/nimbus, this augmentation is automatically applied
 * - Chakra's type system now includes all Nimbus recipes
 * - No consumer-side typegen required!
 */

import '@chakra-ui/react';

declare module '@chakra-ui/react' {
  interface ConfigSlotRecipes {
  nimbusAccordion: SystemSlotRecipeFn<NimbusAccordionSlot, NimbusAccordionVariantProps, NimbusAccordionVariantMap>
  nimbusAlert: SystemSlotRecipeFn<NimbusAlertSlot, NimbusAlertVariantProps, NimbusAlertVariantMap>
  nimbusCalendar: SystemSlotRecipeFn<NimbusCalendarSlot, NimbusCalendarVariantProps, NimbusCalendarVariantMap>
  nimbusCard: SystemSlotRecipeFn<NimbusCardSlot, NimbusCardVariantProps, NimbusCardVariantMap>
  nimbusCheckbox: SystemSlotRecipeFn<NimbusCheckboxSlot, NimbusCheckboxVariantProps, NimbusCheckboxVariantMap>
  nimbusCollapsibleMotion: SystemSlotRecipeFn<NimbusCollapsibleMotionSlot, NimbusCollapsibleMotionVariantProps, NimbusCollapsibleMotionVariantMap>
  nimbusCombobox: SystemSlotRecipeFn<NimbusComboboxSlot, NimbusComboboxVariantProps, NimbusComboboxVariantMap>
  nimbusDataTable: SystemSlotRecipeFn<NimbusDataTableSlot, NimbusDataTableVariantProps, NimbusDataTableVariantMap>
  nimbusDateInput: SystemSlotRecipeFn<NimbusDateInputSlot, NimbusDateInputVariantProps, NimbusDateInputVariantMap>
  nimbusDatePicker: SystemSlotRecipeFn<NimbusDatePickerSlot, NimbusDatePickerVariantProps, NimbusDatePickerVariantMap>
  nimbusDateRangePicker: SystemSlotRecipeFn<NimbusDateRangePickerSlot, NimbusDateRangePickerVariantProps, NimbusDateRangePickerVariantMap>
  nimbusDialog: SystemSlotRecipeFn<NimbusDialogSlot, NimbusDialogVariantProps, NimbusDialogVariantMap>
  nimbusDraggableList: SystemSlotRecipeFn<NimbusDraggableListSlot, NimbusDraggableListVariantProps, NimbusDraggableListVariantMap>
  nimbusDrawer: SystemSlotRecipeFn<NimbusDrawerSlot, NimbusDrawerVariantProps, NimbusDrawerVariantMap>
  nimbusFieldErrors: SystemSlotRecipeFn<NimbusFieldErrorsSlot, NimbusFieldErrorsVariantProps, NimbusFieldErrorsVariantMap>
  nimbusFormField: SystemSlotRecipeFn<NimbusFormFieldSlot, NimbusFormFieldVariantProps, NimbusFormFieldVariantMap>
  nimbusList: SystemSlotRecipeFn<NimbusListSlot, NimbusListVariantProps, NimbusListVariantMap>
  nimbusLocalizedField: SystemSlotRecipeFn<NimbusLocalizedFieldSlot, NimbusLocalizedFieldVariantProps, NimbusLocalizedFieldVariantMap>
  nimbusMenu: SystemSlotRecipeFn<NimbusMenuSlot, NimbusMenuVariantProps, NimbusMenuVariantMap>
  nimbusMoneyInput: SystemSlotRecipeFn<NimbusMoneyInputSlot, NimbusMoneyInputVariantProps, NimbusMoneyInputVariantMap>
  nimbusMultilineTextInput: SystemSlotRecipeFn<NimbusMultilineTextInputSlot, NimbusMultilineTextInputVariantProps, NimbusMultilineTextInputVariantMap>
  nimbusNumberInput: SystemSlotRecipeFn<NimbusNumberInputSlot, NimbusNumberInputVariantProps, NimbusNumberInputVariantMap>
  nimbusProgressBar: SystemSlotRecipeFn<NimbusProgressBarSlot, NimbusProgressBarVariantProps, NimbusProgressBarVariantMap>
  nimbusRadioInput: SystemSlotRecipeFn<NimbusRadioInputSlot, NimbusRadioInputVariantProps, NimbusRadioInputVariantMap>
  nimbusRangeCalendar: SystemSlotRecipeFn<NimbusRangeCalendarSlot, NimbusRangeCalendarVariantProps, NimbusRangeCalendarVariantMap>
  nimbusRichTextInput: SystemSlotRecipeFn<NimbusRichTextInputSlot, NimbusRichTextInputVariantProps, NimbusRichTextInputVariantMap>
  nimbusScopedSearchInput: SystemSlotRecipeFn<NimbusScopedSearchInputSlot, NimbusScopedSearchInputVariantProps, NimbusScopedSearchInputVariantMap>
  nimbusSearchInput: SystemSlotRecipeFn<NimbusSearchInputSlot, NimbusSearchInputVariantProps, NimbusSearchInputVariantMap>
  nimbusSelect: SystemSlotRecipeFn<NimbusSelectSlot, NimbusSelectVariantProps, NimbusSelectVariantMap>
  nimbusSplitButton: SystemSlotRecipeFn<NimbusSplitButtonSlot, NimbusSplitButtonVariantProps, NimbusSplitButtonVariantMap>
  nimbusSwitch: SystemSlotRecipeFn<NimbusSwitchSlot, NimbusSwitchVariantProps, NimbusSwitchVariantMap>
  nimbusTable: SystemSlotRecipeFn<NimbusTableSlot, NimbusTableVariantProps, NimbusTableVariantMap>
  nimbusTabs: SystemSlotRecipeFn<NimbusTabsSlot, NimbusTabsVariantProps, NimbusTabsVariantMap>
  nimbusTagGroup: SystemSlotRecipeFn<NimbusTagGroupSlot, NimbusTagGroupVariantProps, NimbusTagGroupVariantMap>
  nimbusTextInput: SystemSlotRecipeFn<NimbusTextInputSlot, NimbusTextInputVariantProps, NimbusTextInputVariantMap>
  nimbusTimeInput: SystemSlotRecipeFn<NimbusTimeInputSlot, NimbusTimeInputVariantProps, NimbusTimeInputVariantMap>
  nimbusToggleButtonGroup: SystemSlotRecipeFn<NimbusToggleButtonGroupSlot, NimbusToggleButtonGroupVariantProps, NimbusToggleButtonGroupVariantMap>
  }

  interface ConfigRecipes {
  nimbusAvatar: SystemRecipeFn<NimbusAvatarVariantProps, NimbusAvatarVariantMap>
  nimbusBadge: SystemRecipeFn<NimbusBadgeVariantProps, NimbusBadgeVariantMap>
  nimbusButton: SystemRecipeFn<NimbusButtonVariantProps, NimbusButtonVariantMap>
  nimbusCode: SystemRecipeFn<NimbusCodeVariantProps, NimbusCodeVariantMap>
  nimbusGroup: SystemRecipeFn<NimbusGroupVariantProps, NimbusGroupVariantMap>
  nimbusHeading: SystemRecipeFn<NimbusHeadingVariantProps, NimbusHeadingVariantMap>
  nimbusIcon: SystemRecipeFn<NimbusIconVariantProps, NimbusIconVariantMap>
  nimbusKbd: SystemRecipeFn<NimbusKbdVariantProps, NimbusKbdVariantMap>
  nimbusLink: SystemRecipeFn<NimbusLinkVariantProps, NimbusLinkVariantMap>
  nimbusLoadingSpinner: SystemRecipeFn<NimbusLoadingSpinnerVariantProps, NimbusLoadingSpinnerVariantMap>
  nimbusPopover: SystemRecipeFn<NimbusPopoverVariantProps, NimbusPopoverVariantMap>
  nimbusRadioInput: SystemRecipeFn<NimbusRadioInputVariantProps, NimbusRadioInputVariantMap>
  nimbusSeparator: SystemRecipeFn<NimbusSeparatorVariantProps, NimbusSeparatorVariantMap>
  nimbusToggleButton: SystemRecipeFn<NimbusToggleButtonVariantProps, NimbusToggleButtonVariantMap>
  nimbusToolbar: SystemRecipeFn<NimbusToolbarVariantProps, NimbusToolbarVariantMap>
  nimbusTooltip: SystemRecipeFn<NimbusTooltipVariantProps, NimbusTooltipVariantMap>
  }
}
