/**
 * Pre-compiled localized messages for ScopedSearchInput component
 *
 * Generated by scripts/generate-dictionaries.ts
 * DO NOT EDIT MANUALLY
 *
 * @see https://react-spectrum.adobe.com/react-aria/internationalization.html
 */

import { MessageDictionary } from "@internationalized/message";

// Pre-compiled message functions
import scopedSearchInputMessages_en from "./intl/en";
import scopedSearchInputMessages_de from "./intl/de";
import scopedSearchInputMessages_es from "./intl/es";
import scopedSearchInputMessages_fr from "./intl/fr-FR";
import scopedSearchInputMessages_pt from "./intl/pt-BR";

/**
 * Localized string dictionary for ScopedSearchInput component
 * Contains pre-compiled messages for all supported locales
 */
export const scopedSearchInputMessages = new MessageDictionary({
  en: scopedSearchInputMessages_en,
  de: scopedSearchInputMessages_de,
  es: scopedSearchInputMessages_es,
  "fr-FR": scopedSearchInputMessages_fr,
  "pt-BR": scopedSearchInputMessages_pt,
});

/**
 * Available message keys for ScopedSearchInput component
 */
export type ScopedSearchInputMessageKey = "searchLabel" | "selectLabel";
