/**
 * Pre-compiled localized messages for NumberInput component
 *
 * Generated by scripts/generate-dictionaries.ts
 * DO NOT EDIT MANUALLY
 *
 * @see https://react-spectrum.adobe.com/react-aria/internationalization.html
 */

import { MessageDictionary } from "@internationalized/message";

// Pre-compiled message functions
import numberInputMessages_en from "./intl/en";
import numberInputMessages_de from "./intl/de";
import numberInputMessages_es from "./intl/es";
import numberInputMessages_fr from "./intl/fr-FR";
import numberInputMessages_pt from "./intl/pt-BR";

/**
 * Localized string dictionary for NumberInput component
 * Contains pre-compiled messages for all supported locales
 */
export const numberInputMessages = new MessageDictionary({
  en: numberInputMessages_en,
  de: numberInputMessages_de,
  es: numberInputMessages_es,
  "fr-FR": numberInputMessages_fr,
  "pt-BR": numberInputMessages_pt,
});

/**
 * Available message keys for NumberInput component
 */
export type NumberInputMessageKey = "decrement" | "increment";
