/**
 * Pre-compiled localized messages for MoneyInput component
 *
 * Generated by scripts/generate-dictionaries.ts
 * DO NOT EDIT MANUALLY
 *
 * @see https://react-spectrum.adobe.com/react-aria/internationalization.html
 */

import { MessageDictionary } from "@internationalized/message";

// Pre-compiled message functions
import moneyInputMessages_en from "./intl/en";
import moneyInputMessages_de from "./intl/de";
import moneyInputMessages_es from "./intl/es";
import moneyInputMessages_fr from "./intl/fr-FR";
import moneyInputMessages_pt from "./intl/pt-BR";

/**
 * Localized string dictionary for MoneyInput component
 * Contains pre-compiled messages for all supported locales
 */
export const moneyInputMessages = new MessageDictionary({
  en: moneyInputMessages_en,
  de: moneyInputMessages_de,
  es: moneyInputMessages_es,
  "fr-FR": moneyInputMessages_fr,
  "pt-BR": moneyInputMessages_pt,
});

/**
 * Available message keys for MoneyInput component
 */
export type MoneyInputMessageKey =
  | "amountInputLabel"
  | "currencySelectLabel"
  | "highPrecisionPrice";
