/**
 * Pre-compiled localized messages for FieldErrors component
 *
 * Generated by scripts/generate-dictionaries.ts
 * DO NOT EDIT MANUALLY
 *
 * @see https://react-spectrum.adobe.com/react-aria/internationalization.html
 */

import { MessageDictionary } from "@internationalized/message";

// Pre-compiled message functions
import fieldErrorsMessages_en from "./intl/en";
import fieldErrorsMessages_de from "./intl/de";
import fieldErrorsMessages_es from "./intl/es";
import fieldErrorsMessages_fr from "./intl/fr-FR";
import fieldErrorsMessages_pt from "./intl/pt-BR";

/**
 * Normalizes BCP47 locale codes to match dictionary keys.
 * Extracts language code and maps to supported locales: "en", "de", "es", "fr-FR", "pt-BR"
 */
function normalizeLocale(locale: string): string {
  const supportedLocales = new Set(["en", "de", "es", "fr-FR", "pt-BR"]);
  if (supportedLocales.has(locale)) return locale;

  const langMap: Record<string, string> = {
    en: "en",
    de: "de",
    es: "es",
    fr: "fr-FR",
    pt: "pt-BR",
  };

  const lang = locale.split(/[-_]/)[0].toLowerCase();
  return langMap[lang] ?? "en";
}

// Internal dictionary instance
const dictionary = new MessageDictionary({
  en: fieldErrorsMessages_en,
  de: fieldErrorsMessages_de,
  es: fieldErrorsMessages_es,
  "fr-FR": fieldErrorsMessages_fr,
  "pt-BR": fieldErrorsMessages_pt,
});

/**
 * Localized string dictionary for FieldErrors component
 * Contains pre-compiled messages for all supported locales
 * Automatically falls back to English (en) for unsupported locales
 */
export const fieldErrorsMessages = {
  /**
   * Retrieves a simple string message (no variables).
   * Always returns a string (empty string if message not found or is a function).
   * Use this for aria-label and other simple string needs.
   */
  getStringLocale(key: string, locale: string): string {
    const normalizedLocale = normalizeLocale(locale);

    try {
      const message = dictionary.getStringForLocale(key, normalizedLocale);
      // Filter out functions - only return strings
      if (typeof message === "string") return message;
    } catch {
      // Return empty string if message not found
    }

    return "";
  },
};

/**
 * Available message keys for FieldErrors component
 */
export type FieldErrorsMessageKey =
  | "duplicateValue"
  | "emptyValue"
  | "invalidFormat"
  | "invalidFractionalNumber"
  | "invalidFromServer"
  | "invalidNegativeNumber"
  | "invalidValue"
  | "missingRequiredField"
  | "resourceNotFound"
  | "valueAboveMaximum"
  | "valueBelowMinimum"
  | "valueBlocked"
  | "valueOutOfRange"
  | "valueTooLong"
  | "valueTooShort";
