/**
 * Pre-compiled localized messages for FieldErrors component
 *
 * Generated by scripts/generate-dictionaries.ts
 * DO NOT EDIT MANUALLY
 *
 * @see https://react-spectrum.adobe.com/react-aria/internationalization.html
 */

import { MessageDictionary } from "@internationalized/message";

// Pre-compiled message functions
import fieldErrorsMessages_en from "./intl/en";
import fieldErrorsMessages_de from "./intl/de";
import fieldErrorsMessages_es from "./intl/es";
import fieldErrorsMessages_fr from "./intl/fr-FR";
import fieldErrorsMessages_pt from "./intl/pt-BR";

/**
 * Localized string dictionary for FieldErrors component
 * Contains pre-compiled messages for all supported locales
 */
export const fieldErrorsMessages = new MessageDictionary({
  "en-US": fieldErrorsMessages_en,
  "de-DE": fieldErrorsMessages_de,
  "es-ES": fieldErrorsMessages_es,
  "fr-FR": fieldErrorsMessages_fr,
  "pt-BR": fieldErrorsMessages_pt,
});

/**
 * Available message keys for FieldErrors component
 */
export type FieldErrorsMessageKey =
  | "duplicateValue"
  | "emptyValue"
  | "invalidFormat"
  | "invalidFractionalNumber"
  | "invalidFromServer"
  | "invalidNegativeNumber"
  | "invalidValue"
  | "missingRequiredField"
  | "resourceNotFound"
  | "valueAboveMaximum"
  | "valueBelowMinimum"
  | "valueBlocked"
  | "valueOutOfRange"
  | "valueTooLong"
  | "valueTooShort";
