/**
 * Pre-compiled localized messages for DraggableList component
 *
 * Generated by scripts/generate-dictionaries.ts
 * DO NOT EDIT MANUALLY
 *
 * @see https://react-spectrum.adobe.com/react-aria/internationalization.html
 */

import { MessageDictionary, type LocalizedStrings } from "@internationalized/message";

// Pre-compiled message functions
import draggableListMessages_en from "./intl/en";
import draggableListMessages_de from "./intl/de";
import draggableListMessages_es from "./intl/es";
import draggableListMessages_fr from "./intl/fr-FR";
import draggableListMessages_pt from "./intl/pt-BR";

/**
 * Localized string dictionary for DraggableList component
 * Contains pre-compiled messages for all supported locales
 */
export const draggableListMessages = new MessageDictionary({
  "en-US": draggableListMessages_en,
  "de-DE": draggableListMessages_de,
  "es-ES": draggableListMessages_es,
  "fr-FR": draggableListMessages_fr,
  "pt-BR": draggableListMessages_pt,
});

/**
 * Available message keys for DraggableList component
 */
export type DraggableListMessageKey = "emptyMessage" | "removeButtonLabel";
