/**
 * Pre-compiled de messages for FormActionBar
 * Generated by @internationalized/string-compiler
 * DO NOT EDIT MANUALLY
 */

export default {
  ariaLabel: `Formular-Aktionen`,
  cancel: `Abbrechen`,
  delete: `Löschen`,
  save: `Speichern`,
};
