/**
 * Pre-compiled es messages for FormActionBar
 * Generated by @internationalized/string-compiler
 * DO NOT EDIT MANUALLY
 */

export default {
  ariaLabel: `Crear acciones`,
  cancel: `Cancelar`,
  delete: `Eliminar`,
  save: `Guardar`,
};
