/**
 * Pre-compiled fr-FR messages for FormActionBar
 * Generated by @internationalized/string-compiler
 * DO NOT EDIT MANUALLY
 */

export default {
  ariaLabel: `Actions du formulaire`,
  cancel: `Annuler`,
  delete: `Supprimer`,
  save: `Enregistrer`,
};
