/**
 * Pre-compiled pt-BR messages for FormActionBar
 * Generated by @internationalized/string-compiler
 * DO NOT EDIT MANUALLY
 */

export default {
  ariaLabel: `Ações de formulários`,
  cancel: `Cancelar`,
  delete: `Excluir`,
  save: `Salvar`,
};
