/**
 * Pre-compiled localized messages for Pagination component
 *
 * Generated by scripts/generate-dictionaries.ts
 * DO NOT EDIT MANUALLY
 *
 * @see https://react-spectrum.adobe.com/react-aria/internationalization.html
 */

import {
  MessageDictionary,
  type LocalizedStrings,
} from "@internationalized/message";

// Pre-compiled message functions
import paginationMessages_en from "./intl/en";
import paginationMessages_de from "./intl/de";
import paginationMessages_es from "./intl/es";
import paginationMessages_fr from "./intl/fr-FR";
import paginationMessages_pt from "./intl/pt-BR";

/**
 * Type that allows both strings and functions for message values.
 * MessageDictionary accepts both at runtime, but LocalizedStrings only allows strings.
 */
type LocalizedStringsWithFunctions = {
  [lang: string]: {
    [key: string]: string | ((args: Record<string, string | number>) => string);
  };
};

/**
 * Localized string dictionary for Pagination component
 * Contains pre-compiled messages for all supported locales
 */
export const paginationMessages = new MessageDictionary({
  en: paginationMessages_en,
  de: paginationMessages_de,
  es: paginationMessages_es,
  "fr-FR": paginationMessages_fr,
  "pt-BR": paginationMessages_pt,
} as LocalizedStringsWithFunctions as LocalizedStrings);

/**
 * Available message keys for Pagination component
 */
export type PaginationMessageKey =
  | "currentPage"
  | "goToNextPage"
  | "goToPreviousPage"
  | "itemsPerPage"
  | "itemsPerPageText"
  | "ofTotalPages"
  | "args";
