/**
 * Pre-compiled localized messages for Pagination component
 *
 * Generated by scripts/generate-dictionaries.ts
 * DO NOT EDIT MANUALLY
 *
 * @see https://react-spectrum.adobe.com/react-aria/internationalization.html
 */

import {
  MessageDictionary,
  type LocalizedStrings,
} from "@internationalized/message";

// Pre-compiled message functions
import paginationMessages_en from "./intl/en";
import paginationMessages_de from "./intl/de";
import paginationMessages_es from "./intl/es";
import paginationMessages_fr from "./intl/fr-FR";
import paginationMessages_pt from "./intl/pt-BR";

/**
 * Type that allows both strings and functions for message values.
 * MessageDictionary accepts both at runtime, but LocalizedStrings only allows strings.
 */
type LocalizedStringsWithFunctions = {
  [lang: string]: {
    [key: string]: string | ((args: Record<string, string | number>) => string);
  };
};

// Internal dictionary instance
const dictionary = new MessageDictionary({
  en: paginationMessages_en,
  de: paginationMessages_de,
  es: paginationMessages_es,
  "fr-FR": paginationMessages_fr,
  "pt-BR": paginationMessages_pt,
} as LocalizedStringsWithFunctions as LocalizedStrings);

/**
 * Localized string dictionary for Pagination component
 * Contains pre-compiled messages for all supported locales
 * Automatically falls back to English (en) for unsupported locales
 */
export const paginationMessages = {
  /**
   * Retrieves a simple string message (no variables).
   * Always returns a string (empty string if message not found or is a function).
   * Use this for aria-label and other simple string needs.
   */
  getStringLocale(key: string, locale: string): string {
    try {
      const message = dictionary.getStringForLocale(key, locale);
      // Filter out functions - only return strings
      if (typeof message === "string") return message;
    } catch {
      // Continue to fallback
    }

    // Fallback to English
    try {
      const message = dictionary.getStringForLocale(key, "en");
      if (typeof message === "string") return message;
    } catch {
      // Continue to empty string fallback
    }

    // Last resort: return empty string (should never happen in practice)
    return "";
  },

  /**
   * Retrieves a variable message (function that takes arguments).
   * Returns undefined if the message is a simple string or not found.
   * Use this for messages that require variables (e.g., "Hello {name}").
   */
  getVariableLocale(
    key: string,
    locale: string
  ): ((args: Record<string, string | number>) => string) | undefined {
    try {
      const message = dictionary.getStringForLocale(key, locale);
      // Filter out strings - only return functions
      return typeof message === "function" ? message : undefined;
    } catch {
      // Locale not found, fallback to English
      try {
        const message = dictionary.getStringForLocale(key, "en");
        return typeof message === "function" ? message : undefined;
      } catch {
        return undefined;
      }
    }
  },
};

/**
 * Available message keys for Pagination component
 */
export type PaginationMessageKey =
  | "currentPage"
  | "goToNextPage"
  | "goToPreviousPage"
  | "itemsPerPage"
  | "itemsPerPageText"
  | "ofTotalPages"
  | "args";
