packages:
  - packages/*
  - apps/*

catalog:
  '@internationalized/string-compiler': ^3.3.0
  chromatic: ^15.1.0
  '@chromatic-com/storybook': ^5.0.1

catalogMode: strict

catalogs:
  tooling:
    '@fission-ai/openspec': ^1.1.1
    globals: ^17.3.0
    glob: ^11.0.3
    typescript: ~5.9.3
    typescript-eslint: ^8.54.0
    tsx: ^4.21.0
    '@babel/core': ^7.29.0
    '@babel/runtime': ^7.28.6
    '@babel/preset-typescript': ^7.28.5
    '@eslint/js': ^9.39.2
    '@react-types/shared': ^3.33.0
    eslint: ^9.39.2
    eslint-config-prettier: ^10.1.8
    eslint-plugin-prettier: ^5.5.5
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react-refresh: ^0.4.26
    express-rate-limit: ^8.2.1
    prettier: ^3.8.1
    '@preconstruct/cli': ^2.8.12
    '@vitejs/plugin-react': ^5.1.3
    '@vitejs/plugin-react-swc': ^4.2.3
    vite: ^7.3.1
    vite-bundle-analyzer: ^1.3.6
    vite-plugin-dts: ^4.5.4
    vite-tsconfig-paths: ^5.1.4
    rollup: ^4.57.1
    rollup-plugin-tree-shakeable: ^2.0.0
    '@vitest/browser': ^4.0.18
    '@vitest/browser-playwright': ^4.0.18
    '@vitest/coverage-v8': ^4.0.18
    '@testing-library/dom': 10.4.1
    '@testing-library/jest-dom': ^6.9.1
    '@testing-library/user-event': ^14.6.1
    '@testing-library/react': ^16.3.2
    playwright: ^1.58.2
    vitest: ^4.0.18
    storybook: ^10.2.7
    eslint-plugin-storybook: ^10.2.7
    '@storybook/addon-a11y': ^10.2.7
    '@storybook/addon-docs': ^10.2.7
    '@storybook/addon-vitest': ^10.2.7
    '@storybook/react-vite': ^10.2.7
    '@vueless/storybook-dark-mode': ^10.0.7
    jsdom: ^27.4.0
    '@types/jsdom': ^27.0.0
  react:
    '@types/react': ^19.2.13
    '@types/react-dom': ^19.2.3
    react: ^19.0.0
    react-dom: ^19.0.0
    '@emotion/react': ^11.14.0
    '@emotion/is-prop-valid': ^1.4.0
    '@chakra-ui/cli': ^3.32.0
    '@chakra-ui/react': ^3.32.0
    next-themes: ^0.4.6
    react-aria: 3.46.0
    react-aria-components: 1.15.1
    react-stately: 3.44.0
    '@react-aria/interactions': 3.27.0
    '@react-aria/optimize-locales-plugin': 1.1.5
    '@internationalized/date': ^3.11.0
    '@internationalized/string': ^3.2.7
  utils:
    dequal: ^2.0.3
    dompurify: ^3.3.1
    lodash: ^4.17.23
    '@types/lodash': ^4.17.23
    '@types/node': ^24.10.1
