packages:
  - "packages/*"
  - "apps/docs"

catalogs:
  # a dependency that exists in multiple packages can be managed
  # here in a single place via a catalog @see https://pnpm.io/catalogs
  tooling:
    "globals": ^16.0.0
    # typescript
    "typescript": ~5.8.3
    "typescript-eslint": ^8.29.1
    "tsx": ^4.19.3
    # Babel
    "@babel/core": ^7.26.10
    "@babel/preset-typescript": ^7.27.0
    # ESLint + Prettier
    "@eslint/js": ^9.24.0
    "eslint": ^9.24.0
    "eslint-config-prettier": ^10.1.2
    "eslint-plugin-prettier": ^5.2.6
    "eslint-plugin-react-hooks": ^5.2.0
    "eslint-plugin-react-refresh": ^0.4.19
    "prettier": ^3.5.3
    # Preconstruct
    "@preconstruct/cli": ^2.8.12
    # Hygen
    "hygen": ^6.2.11
    # Storybook
    "@storybook/addon-a11y": ^8.6.12
    "@storybook/addon-essentials": ^8.6.12
    "@storybook/experimental-addon-test": ^8.6.12
    "@storybook/preview-api": ^8.6.12
    "@storybook/react": ^8.6.12
    "@storybook/react-vite": ^8.6.12
    "@storybook/test": ^8.6.12
    "storybook": ^8.6.12
    "storybook-dark-mode": ^4.0.2
    # Vite
    "@vitejs/plugin-react": ^4.3.4
    "@vitejs/plugin-react-swc": ^3.8.1
    "vite": ^6.2.6
    "vite-plugin-dts": ^4.5.3
    "vite-tsconfig-paths": ^5.1.4
    # Testing (Vitest, etc.)
    "@vitest/browser": ^3.1.1
    "@vitest/coverage-v8": ^3.1.1
    "@testing-library/user-event": ^14.6.1
    "@testing-library/react": ^16.3.0
    "playwright": ^1.51.1
    "vitest": ^3.1.1

  react:
    # React
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.0.0
    "react": ^19.0.0
    "react-dom": ^19.0.0
    # Emotion
    "@emotion/react": ^11.14.0
    "@emotion/is-prop-valid": ^1.3.1
    # Chakra UI
    "@chakra-ui/cli": ^3.15.1
    "@chakra-ui/react": ^3.15.1
    "@pandacss/types": ^0.53.3
    "next-themes": ^0.4.6
    # React Aria
    "react-aria": ^3.39.0
    "react-aria-components": 1.8.0
    "react-stately": ^3.37.0
  utils:
    "lodash": ^4.17.21
    "@types/lodash": ^4.17.16
    "@types/node": ^22.14.0
