packages:
  - packages/*
  - apps/*

catalog:
  express-rate-limit: ^8.0.1

catalogMode: strict

catalogs:
  tooling:
    globals: ^16.3.0
    glob: ^11.0.3
    typescript: ~5.8.3
    typescript-eslint: ^8.38.0
    tsx: ^4.20.3
    '@babel/core': ^7.28.0
    '@babel/runtime': ^7.27.6
    '@babel/preset-typescript': ^7.27.1
    '@eslint/js': ^9.33.0
    eslint: ^9.32.0
    eslint-config-prettier: ^10.1.8
    eslint-plugin-prettier: ^5.5.4
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react-refresh: ^0.4.20
    prettier: ^3.6.2
    "@preconstruct/cli": ^2.8.12
    hygen: ^6.2.11
    "@vitejs/plugin-react": ^4.4.1
    "@vitejs/plugin-react-swc": ^3.10.2
    vite: ^7.0.5
    vite-bundle-analyzer: ^1.0.0
    vite-plugin-dts: ^4.5.4
    vite-tsconfig-paths: ^5.1.4
    rollup: ^4.48.0
    rollup-plugin-tree-shakeable: ^1.0.3
    "@vitest/browser": ^3.2.4
    "@vitest/coverage-v8": ^3.2.4
    "@testing-library/dom": 10.4.0
    "@testing-library/user-event": ^14.6.1
    "@testing-library/react": ^16.3.0
    playwright: ^1.55.0
    vitest: ^3.2.4
    storybook: ^9.0.18
    eslint-plugin-storybook: ^9.0.18
    "@storybook/addon-a11y": ^9.0.18
    "@storybook/addon-docs": ^9.0.18
    "@storybook/addon-vitest": ^9.0.18
    "@storybook/react-vite": ^9.0.18
    "@vueless/storybook-dark-mode": ^9.0.6
  react:
    "@types/react": ^19.1.8
    "@types/react-dom": ^19.1.6
    react: ^19.0.0
    react-dom: ^19.0.0
    "@emotion/react": ^11.14.0
    "@emotion/is-prop-valid": ^1.3.1
    "@chakra-ui/cli": ^3.17.0
    "@chakra-ui/react": ^3.25.0
    next-themes: ^0.4.6
    react-aria: 3.42.0
    react-aria-components: 1.11.0
    react-stately: 3.40.0
    "@react-aria/interactions": 3.25.4
    "@react-aria/optimize-locales-plugin": 1.1.5
    "@internationalized/date": ^3.8.2
  utils:
    lodash: ^4.17.21
    "@types/lodash": ^4.17.20
    "@types/node": ^24.0.3
