packages:
  - "packages/*"
  - "apps/docs"

catalogs:
  # a depedency that exists in multiple packages can be managed
  # here in a single place via a catalog @see https://pnpm.io/catalogs
  tooling:
    "@babel/core": ^7.26.0
    "@eslint/js": ^9.13.0
    "@preconstruct/cli": ^2.8.10
    "eslint": ^9.13.0
    "globals": ^15.11.0
    "hygen": ^6.2.11
    "tsx": ^4.19.2
    "typescript": ~5.6.3
    "typescript-eslint": ^8.11.0
    "prettier": 3.4.2
    "eslint-config-prettier": ^10.0.1
    "eslint-plugin-prettier": ^5.2.3
