packages:
  - "packages/*"
  - "apps/docs"

catalogs:
  # a depedency that exists in multiple packages can be managed
  # here in a single place via a catalog @see https://pnpm.io/catalogs
  tooling:
    "globals": ^15.11.0
    # typescript
    "typescript": ~5.6.3
    "typescript-eslint": ^8.11.0
    "tsx": ^4.19.2
    # Babel
    "@babel/core": ^7.26.0
    "@babel/preset-typescript": ^7.26.0
    # ESLint + Prettier
    "@eslint/js": ^9.13.0
    "eslint": ^9.13.0
    "eslint-config-prettier": ^10.0.1
    "eslint-plugin-prettier": ^5.2.3
    "eslint-plugin-react-hooks": ^5.0.0
    "eslint-plugin-react-refresh": ^0.4.14
    "prettier": 3.4.2
    # Preconstruct
    "@preconstruct/cli": ^2.8.10
    # Hygen
    "hygen": ^6.2.11
    # Storybook
    "@storybook/addon-a11y": ^8.5.3
    "@storybook/addon-essentials": ^8.5.3
    "@storybook/experimental-addon-test": ^8.5.3
    "@storybook/preview-api": ^8.5.3
    "@storybook/react": ^8.5.3
    "@storybook/react-vite": ^8.5.3
    "@storybook/test": ^8.5.3
    "storybook": ^8.5.3
    "storybook-dark-mode": ^4.0.2
    # Vite
    "@vitejs/plugin-react": ^4.3.4
    "@vitejs/plugin-react-swc": ^3.5.0
    "vite": ^5.4.12
    "vite-plugin-dts": ^4.5.0
    "vite-tsconfig-paths": ^5.1.3
    # Testing (Vitest, etc.)
    "@vitest/browser": ^3.0.5
    "@vitest/coverage-v8": ^3.0.5
    "@testing-library/user-event": ^14.6.1
    "@testing-library/react": ^16.2.0
    "playwright": ^1.50.0
    "vitest": ^3.0.5

  react:
    # React
    "@types/react": ^18.3.12
    "@types/react-dom": ^18.3.1
    "react": ^18.3.1
    "react-dom": ^18.3.1
    # Emotion
    "@emotion/react": ^11.13.3
    "@emotion/is-prop-valid": ^1.3.1
    # Chakra UI
    "@chakra-ui/cli": ^3.2.3
    "@chakra-ui/react": ^3.2.3
    "@pandacss/types": ^0.47.1
    "next-themes": ^0.4.3
  utils:
    "lodash": ^4.17.21
    "@types/lodash": ^4.17.13
