packages:
  - "packages/*"
  - "apps/docs"

catalogs:
  # a depedency that exists in multiple packages can be managed
  # here in a single place via a catalog @see https://pnpm.io/catalogs
  tooling:
    "@babel/core": ^7.26.0
    "@eslint/js": ^9.13.0
    "@preconstruct/cli": ^2.8.10
    "eslint": ^9.13.0
    "globals": ^15.11.0
    "hygen": ^6.2.11
    "tsc": ^2.0.4
    "tsx": ^4.19.2
    "typescript": ~5.6.3
    "typescript-eslint": ^8.11.0
    "vitest": ^3.0.4
    "vite": ^5.4.10
    "vite-plugin-dts": ^4.5.0
    "vite-tsconfig-paths": ^5.1.3
    "@vitejs/plugin-react": ^4.3.4
    "@vitest/browser": ^3.0.4
    "playwright": ^1.50.0
    "@testing-library/user-event": ^14.6.1
