packages:
  - packages/*
  - apps/*

catalog:
  express-rate-limit: ^8.0.1
  dompurify: ^3.3.0

catalogMode: strict

catalogs:
  tooling:
    globals: ^16.4.0
    glob: ^11.0.3
    typescript: ~5.9.3
    typescript-eslint: ^8.46.2
    tsx: ^4.20.6
    "@babel/core": ^7.28.4
    "@babel/runtime": ^7.28.4
    "@babel/preset-typescript": ^7.27.1
    "@eslint/js": ^9.38.0
    eslint: ^9.38.0
    eslint-config-prettier: ^10.1.8
    eslint-plugin-prettier: ^5.5.4
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react-refresh: ^0.4.24
    prettier: ^3.6.2
    "@preconstruct/cli": ^2.8.12
    "@vitejs/plugin-react": ^5.0.4
    "@vitejs/plugin-react-swc": ^4.1.0
    vite: ^7.1.11
    vite-bundle-analyzer: ^1.2.3
    vite-plugin-dts: ^4.5.4
    vite-tsconfig-paths: ^5.1.4
    rollup: ^4.52.5
    rollup-plugin-tree-shakeable: ^2.0.0
    "@vitest/browser": ^4.0.1
    "@vitest/coverage-v8": ^3.2.4
    "@testing-library/dom": 10.4.1
    "@testing-library/jest-dom": ^6.9.1
    "@testing-library/user-event": ^14.6.1
    "@testing-library/react": ^16.3.0
    playwright: ^1.56.1
    vitest: ^3.2.4
    storybook: ^9.1.13
    eslint-plugin-storybook: ^9.1.13
    "@storybook/addon-a11y": ^9.1.13
    "@storybook/addon-docs": ^9.1.13
    "@storybook/addon-vitest": ^9.1.13
    "@storybook/react-vite": ^9.1.13
    "@vueless/storybook-dark-mode": ^9.0.9
    jsdom: ^27.0.1
    "@types/jsdom": ^27.0.0
  react:
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.0.0
    react: ^19.0.0
    react-dom: ^19.0.0
    "@emotion/react": ^11.14.0
    "@emotion/is-prop-valid": ^1.4.0
    "@chakra-ui/cli": ^3.27.1
    "@chakra-ui/react": ^3.27.1
    next-themes: ^0.4.6
    react-aria: 3.44.0
    react-aria-components: 1.13.0
    react-stately: 3.42.0
    "@react-aria/interactions": 3.25.6
    "@react-aria/optimize-locales-plugin": 1.1.5
    "@internationalized/date": ^3.10.0
    react-intl: ^7.1.13
  utils:
    lodash: ^4.17.21
    "@types/lodash": ^4.17.20
    "@types/node": ^24.7.1
