packages:
  - "packages/*"
  - "apps/docs"

catalogs:
  # Can be referenced through "catalog:react17"
  tooling:
    "@babel/core": ^7.26.0
    "@eslint/js": ^9.13.0
    "@preconstruct/cli": ^2.8.10
    "eslint": ^9.13.0
    "globals": ^15.11.0
    "typescript": ~5.6.3
    "typescript-eslint": ^8.11.0
