packages:
  - "packages/*"
  - "apps/*"

catalogs:
  # a dependency that exists in multiple packages can be managed
  # here in a single place via a catalog @see https://pnpm.io/catalogs
  tooling:
    "globals": ^16.0.0
    # typescript
    "typescript": ~5.8.3
    "typescript-eslint": ^8.32.0
    "tsx": ^4.19.4
    # Babel
    "@babel/core": ^7.27.1
    "@babel/runtime": "^7.27.6"
    "@babel/preset-typescript": ^7.27.1
    # ESLint + Prettier
    "@eslint/js": ^9.28.0
    "eslint": ^9.26.0
    "eslint-config-prettier": ^10.1.2
    "eslint-plugin-prettier": ^5.4.0
    "eslint-plugin-react-hooks": ^5.2.0
    "eslint-plugin-react-refresh": ^0.4.20
    "prettier": ^3.5.3
    # Preconstruct
    "@preconstruct/cli": ^2.8.12
    # Hygen
    "hygen": ^6.2.11
    # Storybook
    "@storybook/addon-a11y": ^8.6.14
    "@storybook/addon-essentials": ^8.6.14
    "@storybook/experimental-addon-test": ^8.6.14
    "@storybook/preview-api": ^8.6.14
    "@storybook/react": ^8.6.14
    "@storybook/react-vite": ^8.6.14
    "@storybook/test": ^8.6.14
    "storybook": ^8.6.14
    "storybook-dark-mode": ^4.0.2
    # Vite
    "@vitejs/plugin-react": ^4.4.1
    "@vitejs/plugin-react-swc": ^3.9.0
    "vite": ^6.3.5
    "vite-plugin-dts": ^4.5.4
    "vite-tsconfig-paths": ^5.1.4
    "rollup": "^4.34.2" # used by vite
    # Testing (Vitest, etc.)
    "@vitest/browser": ^3.1.3
    "@vitest/coverage-v8": ^3.1.3
    "@testing-library/user-event": ^14.6.1
    "@testing-library/react": ^16.3.0
    "playwright": ^1.52.0
    "vitest": ^3.1.3

  react:
    # React
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.1.6
    "react": ^19.0.0
    "react-dom": ^19.0.0
    # Emotion
    "@emotion/react": ^11.14.0
    "@emotion/is-prop-valid": ^1.3.1
    # Chakra UI
    "@chakra-ui/cli": ^3.17.0
    "@chakra-ui/react": ^3.19.2
    "@pandacss/types": ^0.53.6
    "next-themes": ^0.4.6
    # React Aria
    "react-aria": "3.39.0"
    "react-aria-components": "1.8.0"
    "react-stately": "3.37.0"
    "@react-aria/optimize-locales-plugin": "1.1.4"
    "@internationalized/date": "^3.8.0"
  utils:
    "lodash": ^4.17.21
    "@types/lodash": ^4.17.16
    "@types/node": ^22.14.0
