packages:
  - packages/*
  - apps/*

catalog:
  express-rate-limit: ^8.0.1
  dompurify: ^3.2.7
  react-intl: ^7.1.11

catalogMode: strict

catalogs:
  tooling:
    globals: ^16.3.0
    glob: ^11.0.3
    typescript: ~5.9.2
    typescript-eslint: ^8.44.1
    tsx: ^4.20.5
    '@babel/core': ^7.28.4
    '@babel/runtime': ^7.28.4
    '@babel/preset-typescript': ^7.27.1
    '@eslint/js': ^9.36.0
    eslint: ^9.36.0
    eslint-config-prettier: ^10.1.8
    eslint-plugin-prettier: ^5.5.4
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react-refresh: ^0.4.22
    prettier: ^3.6.2
    '@preconstruct/cli': ^2.8.12
    '@vitejs/plugin-react': ^5.0.3
    '@vitejs/plugin-react-swc': ^4.0.1
    vite: ^7.1.7
    vite-bundle-analyzer: ^1.2.3
    vite-plugin-dts: ^4.5.4
    vite-tsconfig-paths: ^5.1.4
    rollup: ^4.52.3
    rollup-plugin-tree-shakeable: ^2.0.0
    '@vitest/browser': ^3.2.4
    '@vitest/coverage-v8': ^3.2.4
    '@testing-library/dom': 10.4.1
    '@testing-library/user-event': ^14.6.1
    '@testing-library/react': ^16.3.0
    playwright: ^1.55.1
    vitest: ^3.2.4
    storybook: ^9.1.8
    eslint-plugin-storybook: ^9.1.8
    '@storybook/addon-a11y': ^9.1.8
    '@storybook/addon-docs': ^9.1.8
    '@storybook/addon-vitest': ^9.1.8
    '@storybook/react-vite': ^9.1.8
    '@vueless/storybook-dark-mode': ^9.0.8
  react:
    '@types/react': ^19.1.8
    '@types/react-dom': ^19.1.6
    react: ^19.0.0
    react-dom: ^19.0.0
    '@emotion/react': ^11.14.0
    '@emotion/is-prop-valid': ^1.4.0
    '@chakra-ui/cli': ^3.27.0
    '@chakra-ui/react': ^3.27.0
    next-themes: ^0.4.6
    react-aria: 3.43.2
    react-aria-components: 1.12.2
    react-stately: 3.41.0
    '@react-aria/interactions': 3.25.5
    '@react-aria/optimize-locales-plugin': 1.1.5
    '@internationalized/date': ^3.9.0
    react-intl: ^7.1.11
  utils:
    lodash: ^4.17.21
    '@types/lodash': ^4.17.20
    '@types/node': ^24.3.1
