/**
 * Chakra UI style props that should be filtered out from the main tables
 * These are common styling props from Chakra's style system
 */
export const CHAKRA_STYLE_PROPS = new Set([
  // Layout
  "display",
  "width",
  "w",
  "height",
  "h",
  "minWidth",
  "minW",
  "maxWidth",
  "maxW",
  "minHeight",
  "minH",
  "maxHeight",
  "maxH",
  "overflow",
  "overflowX",
  "overflowY",
  "visibility",

  // Flexbox & Grid
  "flex",
  "flexDirection",
  "flexDir",
  "flexWrap",
  "flexFlow",
  "justifyContent",
  "alignItems",
  "alignContent",
  "justifyItems",
  "justifySelf",
  "alignSelf",
  "gap",
  "rowGap",
  "columnGap",
  "gridColumn",
  "gridRow",
  "gridArea",
  "gridTemplate",
  "gridTemplateColumns",
  "gridTemplateRows",
  "gridTemplateAreas",
  "gridAutoFlow",
  "gridAutoColumns",
  "gridAutoRows",

  // Spacing
  "margin",
  "m",
  "marginTop",
  "mt",
  "marginRight",
  "mr",
  "marginBottom",
  "mb",
  "marginLeft",
  "ml",
  "marginX",
  "mx",
  "marginY",
  "my",
  "padding",
  "p",
  "paddingTop",
  "pt",
  "paddingRight",
  "pr",
  "paddingBottom",
  "pb",
  "paddingLeft",
  "pl",
  "paddingX",
  "px",
  "paddingY",
  "py",

  // Color & Background
  "color",
  "backgroundColor",
  "bg",
  "background",
  "bgColor",
  "opacity",
  "backgroundImage",
  "bgImage",
  "backgroundSize",
  "bgSize",
  "backgroundPosition",
  "bgPosition",
  "backgroundRepeat",
  "bgRepeat",
  "backgroundAttachment",
  "bgAttachment",
  "backgroundClip",
  "bgClip",
  "gradient",

  // Border
  "border",
  "borderWidth",
  "borderStyle",
  "borderColor",
  "borderTop",
  "borderRight",
  "borderBottom",
  "borderLeft",
  "borderX",
  "borderY",
  "borderRadius",
  "borderTopRadius",
  "borderBottomRadius",
  "borderLeftRadius",
  "borderRightRadius",
  "borderTopLeftRadius",
  "borderTopRightRadius",
  "borderBottomLeftRadius",
  "borderBottomRightRadius",

  // Position
  "position",
  "pos",
  "zIndex",
  "top",
  "right",
  "bottom",
  "left",
  "inset",
  "insetX",
  "insetY",

  // Typography
  "fontFamily",
  "fontSize",
  "fontWeight",
  "lineHeight",
  "letterSpacing",
  "textAlign",
  "fontStyle",
  "textTransform",
  "textDecoration",
  "textDecorationColor",
  "textDecorationLine",
  "textDecorationStyle",
  "textDecorationThickness",
  "textUnderlineOffset",
  "textIndent",
  "textOverflow",
  "whiteSpace",
  "wordBreak",
  "wordWrap",
  "overflowWrap",
  "textWrap",

  // Effects
  "boxShadow",
  "shadow",
  "textShadow",
  "filter",
  "backdropFilter",
  "mixBlendMode",
  "backgroundBlendMode",

  // Transforms
  "transform",
  "transformOrigin",
  "scale",
  "scaleX",
  "scaleY",
  "rotate",
  "translateX",
  "translateY",
  "skewX",
  "skewY",

  // Transitions
  "transition",
  "transitionProperty",
  "transitionDuration",
  "transitionTimingFunction",
  "transitionDelay",

  // Cursor & Interaction
  "cursor",
  "pointerEvents",
  "userSelect",
  "resize",

  // List
  "listStyleType",
  "listStylePosition",
  "listStyleImage",

  // Other
  "appearance",
  "content",
  "outline",
  "outlineColor",
  "outlineOffset",
  "outlineWidth",
  "verticalAlign",
  "float",
  "clear",
  "objectFit",
  "objectPosition",
  "isolation",
  "clipPath",
  "mask",
  "maskImage",
  "maskSize",

  // Pseudo states (often passed as props in Chakra)
  "_hover",
  "_focus",
  "_active",
  "_disabled",
  "_selected",
  "_checked",
  "_invalid",
  "_valid",
  "_loading",
  "_expanded",
  "_before",
  "_after",
  "_placeholder",
  "_firstChild",
  "_lastChild",
  "_notFirst",
  "_notLast",
  "_visited",
  "_activeLink",
  "_indeterminate",
  "_groupHover",
  "_groupFocus",
  "_groupActive",
  "_groupDisabled",
  "_groupInvalid",
  "_groupChecked",
  "_groupExpanded",
  "_peerHover",
  "_peerFocus",
  "_peerActive",
  "_peerDisabled",
  "_peerInvalid",
  "_peerChecked",
  "_peerExpanded",
  "_dark",
  "_light",

  // Chakra-specific
  "css",
  "sx",
  "colorPalette",
  "layerStyle",
  "textStyle",
  "apply",
  "styleConfig",
]);
