/**
 * Pre-compiled localized messages for DatePicker component
 *
 * Generated by scripts/generate-dictionaries.ts
 * DO NOT EDIT MANUALLY
 *
 * @see https://react-spectrum.adobe.com/react-aria/internationalization.html
 */

import { MessageDictionary, type LocalizedStrings } from "@internationalized/message";

// Pre-compiled message functions
import datePickerMessages_en from "./intl/en";
import datePickerMessages_de from "./intl/de";
import datePickerMessages_es from "./intl/es";
import datePickerMessages_fr from "./intl/fr-FR";
import datePickerMessages_pt from "./intl/pt-BR";

/**
 * Localized string dictionary for DatePicker component
 * Contains pre-compiled messages for all supported locales
 */
export const datePickerMessages = new MessageDictionary({
  "en-US": datePickerMessages_en,
  "de-DE": datePickerMessages_de,
  "es-ES": datePickerMessages_es,
  "fr-FR": datePickerMessages_fr,
  "pt-BR": datePickerMessages_pt,
});

/**
 * Available message keys for DatePicker component
 */
export type DatePickerMessageKey = "Time.enterTime" | "Time.enterTimeHour" | "Time.enterTimeHourMinute" | "Time.enterTimeHourMinuteSecond" | "Time.startTime" | "clearInput";
