/**
 * Pre-compiled localized messages for PasswordInput component
 *
 * Generated by scripts/generate-dictionaries.ts
 * DO NOT EDIT MANUALLY
 *
 * @see https://react-spectrum.adobe.com/react-aria/internationalization.html
 */

import { MessageDictionary } from "@internationalized/message";

// Pre-compiled message functions
import passwordInputMessages_en from "./intl/en";
import passwordInputMessages_de from "./intl/de";
import passwordInputMessages_es from "./intl/es";
import passwordInputMessages_fr from "./intl/fr-FR";
import passwordInputMessages_pt from "./intl/pt-BR";

/**
 * Normalizes BCP47 locale codes to match dictionary keys.
 * Extracts language code and maps to supported locales: "en", "de", "es", "fr-FR", "pt-BR"
 */
function normalizeLocale(locale: string): string {
  const supportedLocales = new Set(["en", "de", "es", "fr-FR", "pt-BR"]);
  if (supportedLocales.has(locale)) return locale;

  const langMap: Record<string, string> = {
    en: "en",
    de: "de",
    es: "es",
    fr: "fr-FR",
    pt: "pt-BR",
  };

  const lang = locale.split(/[-_]/)[0].toLowerCase();
  return langMap[lang] ?? "en";
}

// Internal dictionary instance
const dictionary = new MessageDictionary({
  en: passwordInputMessages_en,
  de: passwordInputMessages_de,
  es: passwordInputMessages_es,
  "fr-FR": passwordInputMessages_fr,
  "pt-BR": passwordInputMessages_pt,
});

/**
 * Localized string dictionary for PasswordInput component
 * Contains pre-compiled messages for all supported locales
 * Automatically falls back to English (en) for unsupported locales
 */
export const passwordInputMessages = {
  /**
   * Retrieves a simple string message (no variables).
   * Always returns a string (empty string if message not found or is a function).
   * Use this for aria-label and other simple string needs.
   */
  getStringLocale(key: string, locale: string): string {
    const normalizedLocale = normalizeLocale(locale);

    try {
      const message = dictionary.getStringForLocale(key, normalizedLocale);
      // Filter out functions - only return strings
      if (typeof message === "string") return message;
    } catch {
      // Return empty string if message not found
    }

    return "";
  },

  /**
   * Retrieves a variable message (function that takes arguments).
   * Returns undefined if the message is a simple string or not found.
   * Use this for messages that require variables (e.g., "Hello {name}").
   */
  getVariableLocale(
    key: string,
    locale: string
  ): ((args: Record<string, string | number>) => string) | undefined {
    const normalizedLocale = normalizeLocale(locale);

    try {
      const message = dictionary.getStringForLocale(key, normalizedLocale);
      // Filter out strings - only return functions
      return typeof message === "function" ? message : undefined;
    } catch {
      return undefined;
    }
  },
};

/**
 * Available message keys for PasswordInput component
 */
export type PasswordInputMessageKey = "hide" | "show";
