/**
 * Pre-compiled localized messages for PublicPageLayout component
 *
 * Generated by scripts/generate-dictionaries.ts
 * DO NOT EDIT MANUALLY
 *
 * @see https://react-spectrum.adobe.com/react-aria/internationalization.html
 */

import {
  type LocalizedString,
  type LocalizedStrings,
} from "@internationalized/string";
import { normalizeMessages } from "../../../utils/normalize-messages";

// Pre-compiled message functions
import publicPageLayoutMessages_en from "./intl/en";
import publicPageLayoutMessages_de from "./intl/de";
import publicPageLayoutMessages_es from "./intl/es";
import publicPageLayoutMessages_fr from "./intl/fr-FR";
import publicPageLayoutMessages_pt from "./intl/pt-BR";

// Raw LocalizedStrings object for use with useLocalizedStringFormatter hook
export const publicPageLayoutMessagesStrings: LocalizedStrings<
  string,
  LocalizedString
> = {
  en: normalizeMessages(publicPageLayoutMessages_en),
  de: normalizeMessages(publicPageLayoutMessages_de),
  es: normalizeMessages(publicPageLayoutMessages_es),
  "fr-FR": normalizeMessages(publicPageLayoutMessages_fr),
  "pt-BR": normalizeMessages(publicPageLayoutMessages_pt),
} as LocalizedStrings<string, LocalizedString>;

/**
 * Available message keys for PublicPageLayout component
 */
export type PublicPageLayoutMessageKey = "ariaLabel";
