/**
 * Pre-compiled localized messages for TagGroup component
 *
 * Generated by scripts/generate-dictionaries.ts
 * DO NOT EDIT MANUALLY
 *
 * @see https://react-spectrum.adobe.com/react-aria/internationalization.html
 */

import { MessageDictionary } from "@internationalized/message";

// Pre-compiled message functions
import tagGroupMessages_en from "./intl/en";
import tagGroupMessages_de from "./intl/de";
import tagGroupMessages_es from "./intl/es";
import tagGroupMessages_fr from "./intl/fr-FR";
import tagGroupMessages_pt from "./intl/pt-BR";

/**
 * Localized string dictionary for TagGroup component
 * Contains pre-compiled messages for all supported locales
 */
export const tagGroupMessages = new MessageDictionary({
  en: tagGroupMessages_en,
  de: tagGroupMessages_de,
  es: tagGroupMessages_es,
  "fr-FR": tagGroupMessages_fr,
  "pt-BR": tagGroupMessages_pt,
});

/**
 * Available message keys for TagGroup component
 */
export type TagGroupMessageKey = "removeTag";
