/**
 * Pre-compiled localized messages for Alert component
 *
 * Generated by scripts/generate-dictionaries.ts
 * DO NOT EDIT MANUALLY
 *
 * @see https://react-spectrum.adobe.com/react-aria/internationalization.html
 */

import { MessageDictionary } from "@internationalized/message";

// Pre-compiled message functions
import alertMessages_en from "./intl/en";
import alertMessages_de from "./intl/de";
import alertMessages_es from "./intl/es";
import alertMessages_fr from "./intl/fr-FR";
import alertMessages_pt from "./intl/pt-BR";

/**
 * Localized string dictionary for Alert component
 * Contains pre-compiled messages for all supported locales
 */
export const alertMessages = new MessageDictionary({
  "en-US": alertMessages_en,
  "de-DE": alertMessages_de,
  "es-ES": alertMessages_es,
  "fr-FR": alertMessages_fr,
  "pt-BR": alertMessages_pt,
});

/**
 * Available message keys for Alert component
 */
export type AlertMessageKey = "dismiss";
