/**
 * Pre-compiled localized messages for RichTextInput component
 *
 * Generated by scripts/generate-dictionaries.ts
 * DO NOT EDIT MANUALLY
 *
 * @see https://react-spectrum.adobe.com/react-aria/internationalization.html
 */

import { MessageDictionary, type LocalizedStrings } from "@internationalized/message";

// Pre-compiled message functions
import richTextInputMessages_en from "./intl/en";
import richTextInputMessages_de from "./intl/de";
import richTextInputMessages_es from "./intl/es";
import richTextInputMessages_fr from "./intl/fr-FR";
import richTextInputMessages_pt from "./intl/pt-BR";

/**
 * Localized string dictionary for RichTextInput component
 * Contains pre-compiled messages for all supported locales
 */
export const richTextInputMessages = new MessageDictionary({
  "en-US": richTextInputMessages_en,
  "de-DE": richTextInputMessages_de,
  "es-ES": richTextInputMessages_es,
  "fr-FR": richTextInputMessages_fr,
  "pt-BR": richTextInputMessages_pt,
});

/**
 * Available message keys for RichTextInput component
 */
export type RichTextInputMessageKey = "bold" | "bulletedList" | "code" | "headingFive" | "headingFour" | "headingOne" | "headingThree" | "headingTwo" | "italic" | "listFormatting" | "moreFormattingOptions" | "moreStyles" | "numberedList" | "paragraph" | "quote" | "redo" | "strikethrough" | "subscript" | "superscript" | "textFormatting" | "textStyle" | "textStyleMenu" | "underline" | "undo";
