/**
 * Pre-compiled de messages for ComboBox
 * Generated by @internationalized/string-compiler
 * DO NOT EDIT MANUALLY
 */

export default {
  clearSelection: `Auswahl löschen`,
  toggleOptions: `Optionen umschalten`,
  selectedValues: `Ausgewählte Werte`,
  options: `Optionsmenü`,
};
