/**
 * Pre-compiled es messages for ComboBox
 * Generated by @internationalized/string-compiler
 * DO NOT EDIT MANUALLY
 */

export default {
  clearSelection: `Borrar selección`,
  options: `Options menu`,
  selectedValues: `Valores seleccionados`,
  toggleOptions: `Toggle options`,
};
