/**
 * Pre-compiled es messages for ComboBox
 * Generated by @internationalized/string-compiler
 * DO NOT EDIT MANUALLY
 */

export default {
  clearSelection: `Borrar selección`,
  toggleOptions: `Alternar opciones`,
  selectedValues: `Valores seleccionados`,
  options: `Menú de opciones`,
};
