/**
 * Pre-compiled pt-BR messages for ComboBox
 * Generated by @internationalized/string-compiler
 * DO NOT EDIT MANUALLY
 */

export default {
  clearSelection: `Limpar seleção`,
  toggleOptions: `Alternar opções`,
  selectedValues: `Valores selecionados`,
  options: `Menu de opções`,
};
