/**
 * Pre-compiled localized messages for DataTable component
 *
 * Generated by scripts/generate-dictionaries.ts
 * DO NOT EDIT MANUALLY
 *
 * @see https://react-spectrum.adobe.com/react-aria/internationalization.html
 */

import {
  LocalizedStringDictionary,
  type LocalizedString,
  type LocalizedStrings,
} from "@internationalized/string";
import { normalizeMessages } from "../../utils/normalize-messages";

// Pre-compiled message functions
import dataTableMessages_en from "./intl/en";
import dataTableMessages_de from "./intl/de";
import dataTableMessages_es from "./intl/es";
import dataTableMessages_fr from "./intl/fr-FR";
import dataTableMessages_pt from "./intl/pt-BR";

/**
 * Normalizes BCP47 locale codes to match dictionary keys.
 * Extracts language code and maps to supported locales: "en", "de", "es", "fr-FR", "pt-BR"
 *
 * This function is intentionally duplicated in each *.messages.ts file to enable optimal tree-shaking.
 *
 */
function normalizeLocale(locale: string): string {
  const supportedLocales = new Set(["en", "de", "es", "fr-FR", "pt-BR"]);
  if (supportedLocales.has(locale)) return locale;

  const langMap: Record<string, string> = {
    en: "en",
    de: "de",
    es: "es",
    fr: "fr-FR",
    pt: "pt-BR",
  };

  const lang = locale.split(/[-_]/)[0].toLowerCase();
  return langMap[lang] ?? "en";
}

// Internal dictionary instance
const dictionary = new LocalizedStringDictionary<string, LocalizedString>({
  en: normalizeMessages(dataTableMessages_en),
  de: normalizeMessages(dataTableMessages_de),
  es: normalizeMessages(dataTableMessages_es),
  "fr-FR": normalizeMessages(dataTableMessages_fr),
  "pt-BR": normalizeMessages(dataTableMessages_pt),
} as LocalizedStrings<string, LocalizedString>);

/**
 * Localized string dictionary for DataTable component
 * Contains pre-compiled messages for all supported locales
 * Automatically falls back to English (en) for unsupported locales
 */
export const dataTableMessages = {
  /**
   * Retrieves a simple string message (no variables).
   * Always returns a string (empty string if message not found or is a function).
   * Use this for aria-label and other simple string needs.
   */
  getStringLocale(key: string, locale: string): string {
    const normalizedLocale = normalizeLocale(locale);

    try {
      const message = dictionary.getStringForLocale(key, normalizedLocale);
      // Filter out functions - only return strings
      if (typeof message === "string") return message;
    } catch {
      // Return empty string if message not found
    }

    return "";
  },
};

/**
 * Available message keys for DataTable component
 */
export type DataTableMessageKey =
  | "comfortable"
  | "comfortableAriaLabel"
  | "compact"
  | "compactAriaLabel"
  | "dataTable"
  | "dataTableBody"
  | "dataTableHeader"
  | "expandRows"
  | "fullText"
  | "fullTextAriaLabel"
  | "hiddenColumns"
  | "hiddenColumnsAriaLabel"
  | "hideColumn"
  | "layoutSettings"
  | "layoutSettingsAriaLabel"
  | "noHiddenColumns"
  | "pinRows"
  | "reset"
  | "resizeColumn"
  | "rowDensity"
  | "rowDensityAriaLabel"
  | "searchHiddenColumns"
  | "selectRow"
  | "settings"
  | "textPreviews"
  | "textPreviewsAriaLabel"
  | "textVisibility"
  | "textVisibilityAriaLabel"
  | "visibleColumns"
  | "visibleColumnsAria"
  | "visibleColumnsList";
