/**
 * Pre-compiled localized messages for DataTable component
 *
 * Generated by scripts/generate-dictionaries.ts
 * DO NOT EDIT MANUALLY
 *
 * @see https://react-spectrum.adobe.com/react-aria/internationalization.html
 */

import { MessageDictionary } from "@internationalized/message";

// Pre-compiled message functions
import dataTableMessages_en from "./intl/en";
import dataTableMessages_de from "./intl/de";
import dataTableMessages_es from "./intl/es";
import dataTableMessages_fr from "./intl/fr-FR";
import dataTableMessages_pt from "./intl/pt-BR";

/**
 * Localized string dictionary for DataTable component
 * Contains pre-compiled messages for all supported locales
 */
export const dataTableMessages = new MessageDictionary({
  en: dataTableMessages_en,
  de: dataTableMessages_de,
  es: dataTableMessages_es,
  "fr-FR": dataTableMessages_fr,
  "pt-BR": dataTableMessages_pt,
});

/**
 * Available message keys for DataTable component
 */
export type DataTableMessageKey =
  | "comfortable"
  | "comfortableAriaLabel"
  | "compact"
  | "compactAriaLabel"
  | "dataTable"
  | "dataTableBody"
  | "dataTableHeader"
  | "expandRows"
  | "fullText"
  | "fullTextAriaLabel"
  | "hiddenColumns"
  | "hiddenColumnsAriaLabel"
  | "hideColumn"
  | "layoutSettings"
  | "layoutSettingsAriaLabel"
  | "noHiddenColumns"
  | "pinRows"
  | "reset"
  | "resizeColumn"
  | "rowDensity"
  | "rowDensityAriaLabel"
  | "searchHiddenColumns"
  | "selectRow"
  | "settings"
  | "textPreviews"
  | "textPreviewsAriaLabel"
  | "textVisibility"
  | "textVisibilityAriaLabel"
  | "visibleColumns"
  | "visibleColumnsAria"
  | "visibleColumnsList";
