/**
 * Pre-compiled localized messages for LoadingSpinner component
 *
 * Generated by scripts/generate-dictionaries.ts
 * DO NOT EDIT MANUALLY
 *
 * @see https://react-spectrum.adobe.com/react-aria/internationalization.html
 */

import { MessageDictionary } from "@internationalized/message";

// Pre-compiled message functions
import loadingSpinnerMessages_en from "./intl/en";
import loadingSpinnerMessages_de from "./intl/de";
import loadingSpinnerMessages_es from "./intl/es";
import loadingSpinnerMessages_fr from "./intl/fr-FR";
import loadingSpinnerMessages_pt from "./intl/pt-BR";

/**
 * Localized string dictionary for LoadingSpinner component
 * Contains pre-compiled messages for all supported locales
 */
export const loadingSpinnerMessages = new MessageDictionary({
  en: loadingSpinnerMessages_en,
  de: loadingSpinnerMessages_de,
  es: loadingSpinnerMessages_es,
  "fr-FR": loadingSpinnerMessages_fr,
  "pt-BR": loadingSpinnerMessages_pt,
});

/**
 * Available message keys for LoadingSpinner component
 */
export type LoadingSpinnerMessageKey = "default";
