/**
 * Pre-compiled localized messages for LocalizedField component
 *
 * Generated by scripts/generate-dictionaries.ts
 * DO NOT EDIT MANUALLY
 *
 * @see https://react-spectrum.adobe.com/react-aria/internationalization.html
 */

import { MessageDictionary } from "@internationalized/message";

// Pre-compiled message functions
import localizedFieldMessages_en from "./intl/en";
import localizedFieldMessages_de from "./intl/de";
import localizedFieldMessages_es from "./intl/es";
import localizedFieldMessages_fr from "./intl/fr-FR";
import localizedFieldMessages_pt from "./intl/pt-BR";

/**
 * Localized string dictionary for LocalizedField component
 * Contains pre-compiled messages for all supported locales
 */
export const localizedFieldMessages = new MessageDictionary({
  "en-US": localizedFieldMessages_en,
  "de-DE": localizedFieldMessages_de,
  "es-ES": localizedFieldMessages_es,
  "fr-FR": localizedFieldMessages_fr,
  "pt-BR": localizedFieldMessages_pt,
});

/**
 * Available message keys for LocalizedField component
 */
export type LocalizedFieldMessageKey =
  | "hideCurrencies"
  | "hideLanguages"
  | "infoBoxTriggerAriaLabel"
  | "missingRequiredField"
  | "showCurrencies"
  | "showLanguages";
