/**
 * Pre-compiled localized messages for LocalizedField component
 *
 * Generated by scripts/generate-dictionaries.ts
 * DO NOT EDIT MANUALLY
 *
 * @see https://react-spectrum.adobe.com/react-aria/internationalization.html
 */

import {
  LocalizedStringDictionary,
  type LocalizedString,
  type LocalizedStrings,
} from "@internationalized/string";
import { normalizeMessages } from "../../utils/normalize-messages";

// Pre-compiled message functions
import localizedFieldMessages_en from "./intl/en";
import localizedFieldMessages_de from "./intl/de";
import localizedFieldMessages_es from "./intl/es";
import localizedFieldMessages_fr from "./intl/fr-FR";
import localizedFieldMessages_pt from "./intl/pt-BR";

/**
 * Normalizes BCP47 locale codes to match dictionary keys.
 * Extracts language code and maps to supported locales: "en", "de", "es", "fr-FR", "pt-BR"
 *
 * This function is intentionally duplicated in each *.messages.ts file to enable optimal tree-shaking.
 *
 */
function normalizeLocale(locale: string): string {
  const supportedLocales = new Set(["en", "de", "es", "fr-FR", "pt-BR"]);
  if (supportedLocales.has(locale)) return locale;

  const langMap: Record<string, string> = {
    en: "en",
    de: "de",
    es: "es",
    fr: "fr-FR",
    pt: "pt-BR",
  };

  const lang = locale.split(/[-_]/)[0].toLowerCase();
  return langMap[lang] ?? "en";
}

// Internal dictionary instance
const dictionary = new LocalizedStringDictionary<string, LocalizedString>({
  en: normalizeMessages(localizedFieldMessages_en),
  de: normalizeMessages(localizedFieldMessages_de),
  es: normalizeMessages(localizedFieldMessages_es),
  "fr-FR": normalizeMessages(localizedFieldMessages_fr),
  "pt-BR": normalizeMessages(localizedFieldMessages_pt),
} as LocalizedStrings<string, LocalizedString>);

/**
 * Localized string dictionary for LocalizedField component
 * Contains pre-compiled messages for all supported locales
 * Automatically falls back to English (en) for unsupported locales
 */
export const localizedFieldMessages = {
  /**
   * Retrieves a localized message string.
   *
   * Handles both simple and variable messages:
   * - Simple messages (no variables): getVariableLocale(key, locale)
   * - Variable messages: getVariableLocale(key, locale, { variableName: value })
   *
   * For simple messages, args are optional and ignored.
   * For variable messages, args are required and interpolated.
   *
   * Returns empty string if message not found.
   */
  getVariableLocale(
    key: string,
    locale: string,
    args?: Record<string, string | number>
  ): string {
    const normalizedLocale = normalizeLocale(locale);

    try {
      const message = dictionary.getStringForLocale(key, normalizedLocale);

      // If message is a function (has variables), call it with args
      if (typeof message === "function") {
        return message(args ?? {});
      }

      // If message is a string (simple message), return it directly
      if (typeof message === "string") {
        return message;
      }
    } catch {
      // Message not found, return empty string
    }

    return "";
  },
};

/**
 * Available message keys for LocalizedField component
 */
export type LocalizedFieldMessageKey =
  | "hideCurrencies"
  | "hideLanguages"
  | "infoBoxTriggerAriaLabel"
  | "missingRequiredField"
  | "showCurrencies"
  | "showLanguages";
