/**
 * Pre-compiled localized messages for ComboBox component
 *
 * Generated by scripts/generate-dictionaries.ts
 * DO NOT EDIT MANUALLY
 *
 * @see https://react-spectrum.adobe.com/react-aria/internationalization.html
 */

import {
  type LocalizedString,
  type LocalizedStrings,
} from "@internationalized/string";
import { normalizeMessages } from "../../utils/normalize-messages";

// Pre-compiled message functions
import comboBoxMessages_en from "./intl/en";
import comboBoxMessages_de from "./intl/de";
import comboBoxMessages_es from "./intl/es";
import comboBoxMessages_fr from "./intl/fr-FR";
import comboBoxMessages_pt from "./intl/pt-BR";

// Raw LocalizedStrings object for use with useLocalizedStringFormatter hook
export const comboBoxMessagesStrings: LocalizedStrings<
  string,
  LocalizedString
> = {
  en: normalizeMessages(comboBoxMessages_en),
  de: normalizeMessages(comboBoxMessages_de),
  es: normalizeMessages(comboBoxMessages_es),
  "fr-FR": normalizeMessages(comboBoxMessages_fr),
  "pt-BR": normalizeMessages(comboBoxMessages_pt),
} as LocalizedStrings<string, LocalizedString>;

/**
 * Available message keys for ComboBox component
 */
export type ComboBoxMessageKey =
  | "clearSelection"
  | "comboboxDialog"
  | "filterOptions"
  | "options"
  | "selectedValues"
  | "toggleCombobox";
