/**
 * Pre-compiled localized messages for ComboBox component
 *
 * Generated by scripts/generate-dictionaries.ts
 * DO NOT EDIT MANUALLY
 *
 * @see https://react-spectrum.adobe.com/react-aria/internationalization.html
 */

import { MessageDictionary } from "@internationalized/message";

// Pre-compiled message functions
import comboBoxMessages_en from "./intl/en";
import comboBoxMessages_de from "./intl/de";
import comboBoxMessages_es from "./intl/es";
import comboBoxMessages_fr from "./intl/fr-FR";
import comboBoxMessages_pt from "./intl/pt-BR";

/**
 * Localized string dictionary for ComboBox component
 * Contains pre-compiled messages for all supported locales
 */
export const comboBoxMessages = new MessageDictionary({
  en: comboBoxMessages_en,
  de: comboBoxMessages_de,
  es: comboBoxMessages_es,
  "fr-FR": comboBoxMessages_fr,
  "pt-BR": comboBoxMessages_pt,
});

/**
 * Available message keys for ComboBox component
 */
export type ComboBoxMessageKey =
  | "clearSelection"
  | "comboboxDialog"
  | "filterOptions"
  | "options"
  | "selectedValues"
  | "toggleCombobox";
