/**
 * Pre-compiled localized messages for Dialog component
 *
 * Generated by scripts/generate-dictionaries.ts
 * DO NOT EDIT MANUALLY
 *
 * @see https://react-spectrum.adobe.com/react-aria/internationalization.html
 */

import { MessageDictionary } from "@internationalized/message";

// Pre-compiled message functions
import dialogMessages_en from "./intl/en";
import dialogMessages_de from "./intl/de";
import dialogMessages_es from "./intl/es";
import dialogMessages_fr from "./intl/fr-FR";
import dialogMessages_pt from "./intl/pt-BR";

/**
 * Localized string dictionary for Dialog component
 * Contains pre-compiled messages for all supported locales
 */
export const dialogMessages = new MessageDictionary({
  "en-US": dialogMessages_en,
  "de-DE": dialogMessages_de,
  "es-ES": dialogMessages_es,
  "fr-FR": dialogMessages_fr,
  "pt-BR": dialogMessages_pt,
});

/**
 * Available message keys for Dialog component
 */
export type DialogMessageKey = "closeTrigger";
