/**
 * Pre-compiled localized messages for Dialog component
 *
 * Generated by scripts/generate-dictionaries.ts
 * DO NOT EDIT MANUALLY
 *
 * @see https://react-spectrum.adobe.com/react-aria/internationalization.html
 */

import {
  LocalizedStringDictionary,
  type LocalizedString,
  type LocalizedStrings,
} from "@internationalized/string";
import { normalizeMessages } from "../../utils/normalize-messages";

// Pre-compiled message functions
import dialogMessages_en from "./intl/en";
import dialogMessages_de from "./intl/de";
import dialogMessages_es from "./intl/es";
import dialogMessages_fr from "./intl/fr-FR";
import dialogMessages_pt from "./intl/pt-BR";

/**
 * Normalizes BCP47 locale codes to match dictionary keys.
 * Extracts language code and maps to supported locales: "en", "de", "es", "fr-FR", "pt-BR"
 *
 * This function is intentionally duplicated in each *.messages.ts file to enable optimal tree-shaking.
 *
 */
function normalizeLocale(locale: string): string {
  const supportedLocales = new Set(["en", "de", "es", "fr-FR", "pt-BR"]);
  if (supportedLocales.has(locale)) return locale;

  const langMap: Record<string, string> = {
    en: "en",
    de: "de",
    es: "es",
    fr: "fr-FR",
    pt: "pt-BR",
  };

  const lang = locale.split(/[-_]/)[0].toLowerCase();
  return langMap[lang] ?? "en";
}

// Internal dictionary instance
const dictionary = new LocalizedStringDictionary<string, LocalizedString>({
  en: normalizeMessages(dialogMessages_en),
  de: normalizeMessages(dialogMessages_de),
  es: normalizeMessages(dialogMessages_es),
  "fr-FR": normalizeMessages(dialogMessages_fr),
  "pt-BR": normalizeMessages(dialogMessages_pt),
} as LocalizedStrings<string, LocalizedString>);

/**
 * Localized string dictionary for Dialog component
 * Contains pre-compiled messages for all supported locales
 * Automatically falls back to English (en) for unsupported locales
 */
export const dialogMessages = {
  /**
   * Retrieves a simple string message (no variables).
   * Always returns a string (empty string if message not found or is a function).
   * Use this for aria-label and other simple string needs.
   */
  getStringLocale(key: string, locale: string): string {
    const normalizedLocale = normalizeLocale(locale);

    try {
      const message = dictionary.getStringForLocale(key, normalizedLocale);
      // Filter out functions - only return strings
      if (typeof message === "string") return message;
    } catch {
      // Return empty string if message not found
    }

    return "";
  },
};

/**
 * Available message keys for Dialog component
 */
export type DialogMessageKey = "closeTrigger";
