/**
 * Pre-compiled localized messages for RangeCalendar component
 *
 * Generated by scripts/generate-dictionaries.ts
 * DO NOT EDIT MANUALLY
 *
 * @see https://react-spectrum.adobe.com/react-aria/internationalization.html
 */

import { MessageDictionary } from "@internationalized/message";

// Pre-compiled message functions
import rangeCalendarMessages_en from "./intl/en";
import rangeCalendarMessages_de from "./intl/de";
import rangeCalendarMessages_es from "./intl/es";
import rangeCalendarMessages_fr from "./intl/fr-FR";
import rangeCalendarMessages_pt from "./intl/pt-BR";

/**
 * Normalizes BCP47 locale codes to match dictionary keys.
 * Extracts language code and maps to supported locales: "en", "de", "es", "fr-FR", "pt-BR"
 */
function normalizeLocale(locale: string): string {
  const supportedLocales = new Set(["en", "de", "es", "fr-FR", "pt-BR"]);
  if (supportedLocales.has(locale)) return locale;

  const langMap: Record<string, string> = {
    en: "en",
    de: "de",
    es: "es",
    fr: "fr-FR",
    pt: "pt-BR",
  };

  const lang = locale.split(/[-_]/)[0].toLowerCase();
  return langMap[lang] ?? "en";
}

// Internal dictionary instance
const dictionary = new MessageDictionary({
  en: rangeCalendarMessages_en,
  de: rangeCalendarMessages_de,
  es: rangeCalendarMessages_es,
  "fr-FR": rangeCalendarMessages_fr,
  "pt-BR": rangeCalendarMessages_pt,
});

/**
 * Localized string dictionary for RangeCalendar component
 * Contains pre-compiled messages for all supported locales
 * Automatically falls back to English (en) for unsupported locales
 */
export const rangeCalendarMessages = {
  /**
   * Retrieves a simple string message (no variables).
   * Always returns a string (empty string if message not found or is a function).
   * Use this for aria-label and other simple string needs.
   */
  getStringLocale(key: string, locale: string): string {
    const normalizedLocale = normalizeLocale(locale);

    try {
      const message = dictionary.getStringForLocale(key, normalizedLocale);
      // Filter out functions - only return strings
      if (typeof message === "string") return message;
    } catch {
      // Return empty string if message not found
    }

    return "";
  },
};

/**
 * Available message keys for RangeCalendar component
 */
export type RangeCalendarMessageKey =
  | "nextMonth"
  | "nextYear"
  | "previousMonth"
  | "previousYear";
