/**
 * Pre-compiled localized messages for RangeCalendar component
 *
 * Generated by scripts/generate-dictionaries.ts
 * DO NOT EDIT MANUALLY
 *
 * @see https://react-spectrum.adobe.com/react-aria/internationalization.html
 */

import { MessageDictionary, type LocalizedStrings } from "@internationalized/message";

// Pre-compiled message functions
import rangeCalendarMessages_en from "./intl/en";
import rangeCalendarMessages_de from "./intl/de";
import rangeCalendarMessages_es from "./intl/es";
import rangeCalendarMessages_fr from "./intl/fr-FR";
import rangeCalendarMessages_pt from "./intl/pt-BR";

/**
 * Localized string dictionary for RangeCalendar component
 * Contains pre-compiled messages for all supported locales
 */
export const rangeCalendarMessages = new MessageDictionary({
  "en-US": rangeCalendarMessages_en,
  "de-DE": rangeCalendarMessages_de,
  "es-ES": rangeCalendarMessages_es,
  "fr-FR": rangeCalendarMessages_fr,
  "pt-BR": rangeCalendarMessages_pt,
});

/**
 * Available message keys for RangeCalendar component
 */
export type RangeCalendarMessageKey = "nextMonth" | "nextYear" | "previousMonth" | "previousYear";
