/**
 * Pre-compiled localized messages for Drawer component
 *
 * Generated by scripts/generate-dictionaries.ts
 * DO NOT EDIT MANUALLY
 *
 * @see https://react-spectrum.adobe.com/react-aria/internationalization.html
 */

import { MessageDictionary } from "@internationalized/message";

// Pre-compiled message functions
import drawerMessages_en from "./intl/en";
import drawerMessages_de from "./intl/de";
import drawerMessages_es from "./intl/es";
import drawerMessages_fr from "./intl/fr-FR";
import drawerMessages_pt from "./intl/pt-BR";

/**
 * Localized string dictionary for Drawer component
 * Contains pre-compiled messages for all supported locales
 */
export const drawerMessages = new MessageDictionary({
  "en-US": drawerMessages_en,
  "de-DE": drawerMessages_de,
  "es-ES": drawerMessages_es,
  "fr-FR": drawerMessages_fr,
  "pt-BR": drawerMessages_pt,
});

/**
 * Available message keys for Drawer component
 */
export type DrawerMessageKey = "closeTrigger";
