/**
 * Compile component messages to JavaScript
 *
 * Overview:
 * Takes the split component messages (ICU format) and compiles them into
 * pre-compiled JavaScript functions using `@internationalized/string-compiler`.
 * Each component gets its own intl/ directory with compiled message files
 * for each locale.
 *
 * Input:  .temp/by-component/{Component}/{locale}.json (ICU format)
 * Output: packages/nimbus/src/components/{component}/intl/{locale}.ts (compiled JS)
 *
 * Process:
 *   1. Read component messages from split files
 *   2. Compile using `@internationalized/string-compiler`
 *   3. Transform CommonJS → ES modules
 *   4. Write to component's intl/ directory
 *
 * @example
 * Input (.temp/by-component/Alert/en.json):
 *   { "dismiss": "Dismiss" }
 *
 * Output (packages/nimbus/src/components/alert/intl/en.ts):
 *   export default {
 *     "dismiss": () => "Dismiss"
 *   }
 */

import { compileStrings } from "@internationalized/string-compiler";
import fs from "fs/promises";
import path from "path";
import { format } from "prettier";

const LOCALES = [
  { code: "en", bcp47: "en-US" },
  { code: "de", bcp47: "de-DE" },
  { code: "es", bcp47: "es-ES" },
  { code: "fr-FR", bcp47: "fr-FR" },
  { code: "pt-BR", bcp47: "pt-BR" },
] as const;

/**
 * Convert component name to directory name (PascalCase → kebab-case)
 * Example: "Alert" → "alert", "DatePicker" → "date-picker"
 */
function componentToDir(component: string): string {
  return component
    .replace(/([A-Z])/g, "-$1")
    .toLowerCase()
    .replace(/^-/, "");
}

async function compileComponentMessages() {
  const splitDir = path.join(__dirname, "../.temp/by-component");
  const nimbusComponentsDir = path.join(
    __dirname,
    "../../nimbus/src/components"
  );

  // Get all component directories
  const componentDirs = await fs.readdir(splitDir);
  const components = componentDirs.filter((dir) =>
    fs
      .stat(path.join(splitDir, dir))
      .then((stat) => stat.isDirectory())
      .catch(() => false)
  );

  console.log(`🔨 Compiling messages for ${components.length} components...\n`);

  for (const component of components) {
    const componentDir = path.join(splitDir, component);
    const componentDirName = componentToDir(component);
    const outputIntlDir = path.join(
      nimbusComponentsDir,
      componentDirName,
      "intl"
    );

    // Create intl directory
    await fs.mkdir(outputIntlDir, { recursive: true });

    console.log(`📦 ${component} (${componentDirName}/)`);

    // Process each locale
    for (const locale of LOCALES) {
      const inputPath = path.join(componentDir, `${locale.code}.json`);

      // Check if file exists (some components might not have all locales)
      try {
        await fs.access(inputPath);
      } catch {
        console.log(`   ⚠️  Skipping ${locale.code} (file not found)`);
        continue;
      }

      // Read ICU messages
      const messages = JSON.parse(await fs.readFile(inputPath, "utf-8"));

      // Compile using string-compiler
      const compiledCode = compileStrings(messages);

      // Transform CommonJS → ES modules
      let esModuleCode = compiledCode.replace(
        /^module\.exports\s*=\s*/,
        "export default "
      );

      // Add type annotations to function parameters to fix TypeScript errors
      // Replace (args) => with (args: Record<string, MessageValue>) =>
      // Using MessageValue union type for type-safe ICU message variables
      esModuleCode = esModuleCode.replace(
        /\(args\)\s*=>/g,
        "(args: Record<string, string | number>) =>"
      );

      // Write compiled file
      const outputPath = path.join(outputIntlDir, `${locale.code}.ts`);
      const tsContent = `/**
 * Pre-compiled ${locale.code} messages for ${component}
 * Generated by @internationalized/string-compiler
 * DO NOT EDIT MANUALLY
 */

${esModuleCode}`;

      // Format the entire file content with Prettier
      const formattedContent = await format(tsContent, {
        parser: "typescript",
        singleQuote: false,
        printWidth: 80,
      });

      await fs.writeFile(outputPath, formattedContent);
      console.log(`   ✅ ${locale.code}`);
    }
  }

  console.log(`\n✅ Compilation complete!`);
}

compileComponentMessages().catch(console.error);
