/**
 * Pre-compiled localized messages for Select component
 *
 * Generated by scripts/generate-dictionaries.ts
 * DO NOT EDIT MANUALLY
 *
 * @see https://react-spectrum.adobe.com/react-aria/internationalization.html
 */

import { MessageDictionary } from "@internationalized/message";

// Pre-compiled message functions
import selectMessages_en from "./intl/en";
import selectMessages_de from "./intl/de";
import selectMessages_es from "./intl/es";
import selectMessages_fr from "./intl/fr-FR";
import selectMessages_pt from "./intl/pt-BR";

/**
 * Localized string dictionary for Select component
 * Contains pre-compiled messages for all supported locales
 */
export const selectMessages = new MessageDictionary({
  en: selectMessages_en,
  de: selectMessages_de,
  es: selectMessages_es,
  "fr-FR": selectMessages_fr,
  "pt-BR": selectMessages_pt,
});

/**
 * Available message keys for Select component
 */
export type SelectMessageKey = "clearSelection";
