/**
 * Pre-compiled localized messages for Calendar component
 *
 * Generated by scripts/generate-dictionaries.ts
 * DO NOT EDIT MANUALLY
 *
 * @see https://react-spectrum.adobe.com/react-aria/internationalization.html
 */

import { MessageDictionary, type LocalizedStrings } from "@internationalized/message";

// Pre-compiled message functions
import calendarMessages_en from "./intl/en";
import calendarMessages_de from "./intl/de";
import calendarMessages_es from "./intl/es";
import calendarMessages_fr from "./intl/fr-FR";
import calendarMessages_pt from "./intl/pt-BR";

/**
 * Localized string dictionary for Calendar component
 * Contains pre-compiled messages for all supported locales
 */
export const calendarMessages = new MessageDictionary({
  "en-US": calendarMessages_en,
  "de-DE": calendarMessages_de,
  "es-ES": calendarMessages_es,
  "fr-FR": calendarMessages_fr,
  "pt-BR": calendarMessages_pt,
});

/**
 * Available message keys for Calendar component
 */
export type CalendarMessageKey = "nextMonth" | "nextYear" | "previousMonth" | "previousYear";
