/**
 * Pre-compiled localized messages for Avatar component
 *
 * Generated by scripts/generate-dictionaries.ts
 * DO NOT EDIT MANUALLY
 *
 * @see https://react-spectrum.adobe.com/react-aria/internationalization.html
 */

import { MessageDictionary, type LocalizedStrings } from "@internationalized/message";

// Pre-compiled message functions
import avatarMessages_en from "./intl/en";
import avatarMessages_de from "./intl/de";
import avatarMessages_es from "./intl/es";
import avatarMessages_fr from "./intl/fr-FR";
import avatarMessages_pt from "./intl/pt-BR";

/**
 * Type that allows both strings and functions for message values.
 * MessageDictionary accepts both at runtime, but LocalizedStrings only allows strings.
 */
type LocalizedStringsWithFunctions = {
  [lang: string]: {
    [key: string]: string | ((args: Record<string, string | number>) => string);
  };
};

/**
 * Localized string dictionary for Avatar component
 * Contains pre-compiled messages for all supported locales
 */
export const avatarMessages = new MessageDictionary({
  "en-US": avatarMessages_en,
  "de-DE": avatarMessages_de,
  "es-ES": avatarMessages_es,
  "fr-FR": avatarMessages_fr,
  "pt-BR": avatarMessages_pt,
} as LocalizedStringsWithFunctions as LocalizedStrings);

/**
 * Available message keys for Avatar component
 */
export type AvatarMessageKey = "avatarLabel";
