/**
 * Pre-compiled de messages for Avatar
 * Generated by @internationalized/string-compiler
 * DO NOT EDIT MANUALLY
 */

export default {
  avatarLabel: (args: Record<string, any>) => `Avatarbild für ${args.fullName}`,
};
