/**
 * Pre-compiled fr-FR messages for Avatar
 * Generated by @internationalized/string-compiler
 * DO NOT EDIT MANUALLY
 */

export default {
  avatarLabel: (args: Record<string, any>) =>
    `Image d'avatar pour ${args.fullName}`,
};
