/**
 * Pre-compiled pt-BR messages for Avatar
 * Generated by @internationalized/string-compiler
 * DO NOT EDIT MANUALLY
 */

export default {  "avatarLabel": (args: Record<string, any>) => `Avatar para ${args.fullName}`,
}
