/**
 * Pre-compiled localized messages for SplitButton component
 *
 * Generated by scripts/generate-dictionaries.ts
 * DO NOT EDIT MANUALLY
 *
 * @see https://react-spectrum.adobe.com/react-aria/internationalization.html
 */

import { MessageDictionary } from "@internationalized/message";

// Pre-compiled message functions
import splitButtonMessages_en from "./intl/en";
import splitButtonMessages_de from "./intl/de";
import splitButtonMessages_es from "./intl/es";
import splitButtonMessages_fr from "./intl/fr-FR";
import splitButtonMessages_pt from "./intl/pt-BR";

/**
 * Localized string dictionary for SplitButton component
 * Contains pre-compiled messages for all supported locales
 */
export const splitButtonMessages = new MessageDictionary({
  "en-US": splitButtonMessages_en,
  "de-DE": splitButtonMessages_de,
  "es-ES": splitButtonMessages_es,
  "fr-FR": splitButtonMessages_fr,
  "pt-BR": splitButtonMessages_pt,
});

/**
 * Available message keys for SplitButton component
 */
export type SplitButtonMessageKey = "noActionsAvailable";
