import { describe, it, expect } from "vitest";
import { getIconCatalog } from "./data-loader.js";

/**
 * Data integrity tests for the bundled icon catalog (data/icons.json).
 *
 * These tests validate that the catalog generated by
 * `scripts/build-icon-catalog.ts` has the correct structure and content.
 * Run `pnpm --filter @commercetools/nimbus-mcp catalog:icons` to regenerate.
 */
describe("icon catalog — structure", () => {
  it("has required top-level fields", async () => {
    const catalog = await getIconCatalog();

    expect(typeof catalog.generated).toBe("string");
    expect(new Date(catalog.generated).toISOString()).toBe(catalog.generated);
    expect(typeof catalog.count).toBe("number");
    expect(Array.isArray(catalog.icons)).toBe(true);
  });

  it("count matches icons array length", async () => {
    const catalog = await getIconCatalog();
    expect(catalog.count).toBe(catalog.icons.length);
  });

  it("every entry has name, importPath, category, and keywords", async () => {
    const catalog = await getIconCatalog();

    for (const icon of catalog.icons) {
      expect(typeof icon.name).toBe("string");
      expect(icon.name.length).toBeGreaterThan(0);
      expect(icon.importPath).toBe("@commercetools/nimbus-icons");
      expect(["material", "custom"]).toContain(icon.category);
      expect(Array.isArray(icon.keywords)).toBe(true);
      expect(icon.keywords.length).toBeGreaterThan(0);
    }
  });

  it("all keywords are lowercase strings", async () => {
    const catalog = await getIconCatalog();

    for (const icon of catalog.icons) {
      for (const keyword of icon.keywords) {
        expect(typeof keyword).toBe("string");
        expect(keyword).toBe(keyword.toLowerCase());
      }
    }
  });
});

describe("icon catalog — counts", () => {
  it("contains 2100+ Material icons", async () => {
    const catalog = await getIconCatalog();
    const materialCount = catalog.icons.filter(
      (i) => i.category === "material"
    ).length;
    expect(materialCount).toBeGreaterThanOrEqual(2100);
  });

  it("contains 5+ custom icons", async () => {
    const catalog = await getIconCatalog();
    const customCount = catalog.icons.filter(
      (i) => i.category === "custom"
    ).length;
    expect(customCount).toBeGreaterThanOrEqual(5);
  });
});

describe("icon catalog — spot checks", () => {
  it("CheckCircle has expected semantic keywords", async () => {
    const catalog = await getIconCatalog();
    const entry = catalog.icons.find((i) => i.name === "CheckCircle");

    expect(entry).toBeDefined();
    expect(entry?.category).toBe("custom");
    expect(entry?.keywords).toContain("check");
    expect(entry?.keywords).toContain("circle");
    expect(entry?.keywords).toContain("done");
    expect(entry?.keywords).toContain("success");
  });

  it("AccountCircle splits into account and circle keywords", async () => {
    const catalog = await getIconCatalog();
    const entry = catalog.icons.find((i) => i.name === "AccountCircle");

    expect(entry).toBeDefined();
    expect(entry?.category).toBe("material");
    expect(entry?.keywords).toContain("account");
    expect(entry?.keywords).toContain("circle");
  });

  it("CommercetoolsCube is present as a custom icon", async () => {
    const catalog = await getIconCatalog();
    const entry = catalog.icons.find((i) => i.name === "CommercetoolsCube");

    expect(entry).toBeDefined();
    expect(entry?.category).toBe("custom");
    expect(entry?.keywords).toContain("commercetools");
    expect(entry?.keywords).toContain("cube");
  });

  it("no entry names are duplicated", async () => {
    const catalog = await getIconCatalog();
    const names = catalog.icons.map((i) => i.name);
    const uniqueNames = new Set(names);
    expect(uniqueNames.size).toBe(names.length);
  });
});
