name: CI

description: Shared action with basic setup for each job

runs:
  using: composite

  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4.0.0
      with:
        run_install: false

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: "24.12"
        cache: pnpm

    - name: Update npm to latest
      run: npm install -g npm@latest
      shell: bash

    - name: Install dependencies
      run: pnpm install
      shell: bash

    - name: Build design tokens
      run: pnpm build:tokens
      shell: bash

    - name: Extract and compile i18n messages
      # Generates *.messages.ts and intl/*.ts files (gitignored) required at build time
      run: pnpm extract-intl
      shell: bash

    - name: Build packages
      # Skip docs build - Vercel handles docs deployment separately
      run: pnpm build:packages
      shell: bash
