name: CI

description: Shared action with basic setup for each job

runs:
  using: composite

  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4.0.0
      with:
        run_install: false

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: pnpm

    - name: Install dependencies
      run: pnpm install
      shell: bash

    - name: Building packages
      run: pnpm build
      shell: bash
