name: CI

description: Shared action with basic setup for each job

runs:
  using: composite

  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4.0.0
      with:
        run_install: false

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: "24.12"
        cache: pnpm

    - name: Update npm to latest
      run: npm install -g npm@latest
      shell: bash

    - name: Install dependencies
      run: pnpm install
      shell: bash

    - name: Building packages
      # Skip docs build - saves disk space and build time
      # Vercel handles docs deployment and builds them separately
      run: pnpm build:tokens && pnpm build:packages
      shell: bash
