/**
 * Pre-compiled localized messages for DateRangePicker component
 *
 * Generated by scripts/generate-dictionaries.ts
 * DO NOT EDIT MANUALLY
 *
 * @see https://react-spectrum.adobe.com/react-aria/internationalization.html
 */

import { MessageDictionary, type LocalizedStrings } from "@internationalized/message";

// Pre-compiled message functions
import dateRangePickerMessages_en from "./intl/en";
import dateRangePickerMessages_de from "./intl/de";
import dateRangePickerMessages_es from "./intl/es";
import dateRangePickerMessages_fr from "./intl/fr-FR";
import dateRangePickerMessages_pt from "./intl/pt-BR";

/**
 * Localized string dictionary for DateRangePicker component
 * Contains pre-compiled messages for all supported locales
 */
export const dateRangePickerMessages = new MessageDictionary({
  "en-US": dateRangePickerMessages_en,
  "de-DE": dateRangePickerMessages_de,
  "es-ES": dateRangePickerMessages_es,
  "fr-FR": dateRangePickerMessages_fr,
  "pt-BR": dateRangePickerMessages_pt,
});

/**
 * Available message keys for DateRangePicker component
 */
export type DateRangePickerMessageKey = "clearInput" | "clearSelection" | "endTime" | "endTimeHour" | "endTimeHourMinute" | "endTimeHourMinuteSecond" | "endTimeLabel" | "openCalendar" | "startTime" | "startTimeHour" | "startTimeHourMinute" | "startTimeHourMinuteSecond" | "startTimeLabel";
