/**
 * Pre-compiled localized messages for DateRangePicker component
 *
 * Generated by scripts/generate-dictionaries.ts
 * DO NOT EDIT MANUALLY
 *
 * @see https://react-spectrum.adobe.com/react-aria/internationalization.html
 */

import { MessageDictionary } from "@internationalized/message";

// Pre-compiled message functions
import dateRangePickerMessages_en from "./intl/en";
import dateRangePickerMessages_de from "./intl/de";
import dateRangePickerMessages_es from "./intl/es";
import dateRangePickerMessages_fr from "./intl/fr-FR";
import dateRangePickerMessages_pt from "./intl/pt-BR";

/**
 * Normalizes BCP47 locale codes to match dictionary keys.
 * Extracts language code and maps to supported locales: "en", "de", "es", "fr-FR", "pt-BR"
 *
 * This function is intentionally duplicated in each *.messages.ts file to enable optimal tree-shaking.
 *
 */
function normalizeLocale(locale: string): string {
  const supportedLocales = new Set(["en", "de", "es", "fr-FR", "pt-BR"]);
  if (supportedLocales.has(locale)) return locale;

  const langMap: Record<string, string> = {
    en: "en",
    de: "de",
    es: "es",
    fr: "fr-FR",
    pt: "pt-BR",
  };

  const lang = locale.split(/[-_]/)[0].toLowerCase();
  return langMap[lang] ?? "en";
}

// Internal dictionary instance
const dictionary = new MessageDictionary({
  en: dateRangePickerMessages_en,
  de: dateRangePickerMessages_de,
  es: dateRangePickerMessages_es,
  "fr-FR": dateRangePickerMessages_fr,
  "pt-BR": dateRangePickerMessages_pt,
});

/**
 * Localized string dictionary for DateRangePicker component
 * Contains pre-compiled messages for all supported locales
 * Automatically falls back to English (en) for unsupported locales
 */
export const dateRangePickerMessages = {
  /**
   * Retrieves a simple string message (no variables).
   * Always returns a string (empty string if message not found or is a function).
   * Use this for aria-label and other simple string needs.
   */
  getStringLocale(key: string, locale: string): string {
    const normalizedLocale = normalizeLocale(locale);

    try {
      const message = dictionary.getStringForLocale(key, normalizedLocale);
      // Filter out functions - only return strings
      if (typeof message === "string") return message;
    } catch {
      // Return empty string if message not found
    }

    return "";
  },
};

/**
 * Available message keys for DateRangePicker component
 */
export type DateRangePickerMessageKey =
  | "clearInput"
  | "clearSelection"
  | "endTime"
  | "endTimeHour"
  | "endTimeHourMinute"
  | "endTimeHourMinuteSecond"
  | "endTimeLabel"
  | "openCalendar"
  | "startTime"
  | "startTimeHour"
  | "startTimeHourMinute"
  | "startTimeHourMinuteSecond"
  | "startTimeLabel";
