/**
 * Search metadata for the icon set, keyed by export name (e.g. `AccountCircle`,
 * `Svg10k`, `Figma`). Generated by scripts/sync-meta.ts — see that script.
 *
 * Exposed only via the `@commercetools/nimbus-icons/meta` subpath — it is
 * intentionally NOT re-exported from the package barrel, so
 * `import * as Icons from "@commercetools/nimbus-icons"` never pulls in this
 * ~900KB payload. Import it explicitly (ideally lazily) when you need it.
 */
import metadata from "./meta.generated.json";

import type { IconMeta } from "./custom-icons-meta";

export type { IconMeta };

export const iconMetadata: Record<string, IconMeta> = metadata;
