/**
 * Pre-compiled localized messages for DetailPage component
 *
 * Generated by scripts/generate-dictionaries.ts
 * DO NOT EDIT MANUALLY
 *
 * @see https://react-spectrum.adobe.com/react-aria/internationalization.html
 */

import {
  type LocalizedString,
  type LocalizedStrings,
} from "@internationalized/string";
import { normalizeMessages } from "../../utils/normalize-messages";

// Pre-compiled message functions
import detailPageMessages_en from "./intl/en";
import detailPageMessages_de from "./intl/de";
import detailPageMessages_es from "./intl/es";
import detailPageMessages_fr from "./intl/fr-FR";
import detailPageMessages_pt from "./intl/pt-BR";

// Raw LocalizedStrings object for use with useLocalizedStringFormatter hook
export const detailPageMessagesStrings: LocalizedStrings<
  string,
  LocalizedString
> = {
  en: normalizeMessages(detailPageMessages_en),
  de: normalizeMessages(detailPageMessages_de),
  es: normalizeMessages(detailPageMessages_es),
  "fr-FR": normalizeMessages(detailPageMessages_fr),
  "pt-BR": normalizeMessages(detailPageMessages_pt),
} as LocalizedStrings<string, LocalizedString>;

/**
 * Available message keys for DetailPage component
 */
export type DetailPageMessageKey = "backLink";
