/**
 * Pre-compiled localized messages for FormDialog component
 *
 * Generated by scripts/generate-dictionaries.ts
 * DO NOT EDIT MANUALLY
 *
 * @see https://react-spectrum.adobe.com/react-aria/internationalization.html
 */

import {
  type LocalizedString,
  type LocalizedStrings,
} from "@internationalized/string";
import { normalizeMessages } from "../../../utils/normalize-messages";

// Pre-compiled message functions
import formDialogMessages_en from "./intl/en";
import formDialogMessages_de from "./intl/de";
import formDialogMessages_es from "./intl/es";
import formDialogMessages_fr from "./intl/fr-FR";
import formDialogMessages_pt from "./intl/pt-BR";

// Raw LocalizedStrings object for use with useLocalizedStringFormatter hook
export const formDialogMessagesStrings: LocalizedStrings<
  string,
  LocalizedString
> = {
  en: normalizeMessages(formDialogMessages_en),
  de: normalizeMessages(formDialogMessages_de),
  es: normalizeMessages(formDialogMessages_es),
  "fr-FR": normalizeMessages(formDialogMessages_fr),
  "pt-BR": normalizeMessages(formDialogMessages_pt),
} as LocalizedStrings<string, LocalizedString>;

/**
 * Available message keys for FormDialog component
 */
export type FormDialogMessageKey = "cancel" | "save";
