/**
 * Search metadata for the icon set, keyed by export name (e.g. `AccountCircle`,
 * `Svg10k`, `Figma`). Generated by apps/docs/scripts/sync-icon-meta.ts.
 *
 * Docs-app-only: this catalog powers the icon explorer's search and filtering.
 * It is intentionally NOT part of the published `@commercetools/nimbus-icons`
 * surface — it's generated and consumed entirely within the docs app, and
 * loaded lazily (its own ~900KB chunk) so it never enters the main bundle.
 */
import metadata from "./icon-meta.generated.json";

import type { IconMeta } from "./custom-icons-meta";

export type { IconMeta };

export const iconMetadata: Record<string, IconMeta> = metadata;
