/**
 * Pre-compiled localized messages for ConfirmationDialog component
 *
 * Generated by scripts/generate-dictionaries.ts
 * DO NOT EDIT MANUALLY
 *
 * @see https://react-spectrum.adobe.com/react-aria/internationalization.html
 */

import {
  type LocalizedString,
  type LocalizedStrings,
} from "@internationalized/string";
import { normalizeMessages } from "../../../utils/normalize-messages";

// Pre-compiled message functions
import confirmationDialogMessages_en from "./intl/en";
import confirmationDialogMessages_de from "./intl/de";
import confirmationDialogMessages_es from "./intl/es";
import confirmationDialogMessages_fr from "./intl/fr-FR";
import confirmationDialogMessages_pt from "./intl/pt-BR";

// Raw LocalizedStrings object for use with useLocalizedStringFormatter hook
export const confirmationDialogMessagesStrings: LocalizedStrings<
  string,
  LocalizedString
> = {
  en: normalizeMessages(confirmationDialogMessages_en),
  de: normalizeMessages(confirmationDialogMessages_de),
  es: normalizeMessages(confirmationDialogMessages_es),
  "fr-FR": normalizeMessages(confirmationDialogMessages_fr),
  "pt-BR": normalizeMessages(confirmationDialogMessages_pt),
} as LocalizedStrings<string, LocalizedString>;

/**
 * Available message keys for ConfirmationDialog component
 */
export type ConfirmationDialogMessageKey = "cancel" | "confirm";
