name: Chromatic

on:
  push:
    branches:
      - main
    paths:
      - "packages/nimbus/**"
      - "!packages/nimbus/chromatic.config.json"
      - "!packages/nimbus/.storybook/main.ts"
      - "!packages/nimbus/package.json"
      - "packages/tokens/**"
      - "packages/nimbus-icons/**"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "packages/nimbus/**"
      - "!packages/nimbus/chromatic.config.json"
      - "!packages/nimbus/.storybook/main.ts"
      - "!packages/nimbus/package.json"
      - "packages/tokens/**"
      - "packages/nimbus-icons/**"

jobs:
  chromatic:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false || github.event_name == 'push'
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Installing dependencies and building packages
        uses: ./.github/actions/ci

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true
          storybookBaseDir: packages/nimbus
          buildScriptName: build-storybook
          zip: true
