name: Chromatic

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  chromatic:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false || github.event_name == 'push'
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          since_last_remote_commit: true
          files: |
            packages/nimbus/**
            packages/tokens/**
            packages/nimbus-icons/**
          files_ignore: |
            packages/nimbus/chromatic.config.json
            packages/nimbus/.storybook/main.ts
            packages/nimbus/package.json

      - name: Installing dependencies and building packages
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: ./.github/actions/ci

      - name: Run Chromatic
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: false
          storybookBaseDir: packages/nimbus
          buildScriptName: build-storybook
          zip: true
