name: Add changeset to Renovate PR

on:
  pull_request_target:
    types: [opened, synchronize, labeled]
    branches:
      - main
    paths:
      - '**/package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'

jobs:
  changeset:
    uses: commercetools/merchant-center-application-kit/.github/workflows/renovate-changeset.yml@main
    with:
      package-dirs: 'packages'
    secrets: inherit
