name: Test Nimbus Components in Deployed Storybook
permissions:
  contents: read
on: deployment_status
jobs:
  test-storybook-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.deployment_status.state == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build the project
        run: pnpm build:tokens && pnpm run build:packages # no reason to build docs since they have no tests, if that changes we should build them
        env:
          NODE_ENV: production

      # - name: Lint # this takes surprisingly long and why bother if we're going to continue if it fails?
      #   run: pnpm lint
      #   continue-on-error: true # continue even if linting fails (for now) TODO: typechecking once we feel ok failing on lint

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps chromium

      - name: Run tests
        run: pnpm test
        timeout-minutes: 5 # Cancel this job after 5 minutes
        env:
          NODE_ENV: production
          SB_URL: "${{ github.event.deployment_status.target_url }}"
