/**
 * Pre-compiled localized messages for SearchInput component
 *
 * Generated by scripts/generate-dictionaries.ts
 * DO NOT EDIT MANUALLY
 *
 * @see https://react-spectrum.adobe.com/react-aria/internationalization.html
 */

import { MessageDictionary } from "@internationalized/message";

// Pre-compiled message functions
import searchInputMessages_en from "./intl/en";
import searchInputMessages_de from "./intl/de";
import searchInputMessages_es from "./intl/es";
import searchInputMessages_fr from "./intl/fr-FR";
import searchInputMessages_pt from "./intl/pt-BR";

/**
 * Localized string dictionary for SearchInput component
 * Contains pre-compiled messages for all supported locales
 */
export const searchInputMessages = new MessageDictionary({
  "en-US": searchInputMessages_en,
  "de-DE": searchInputMessages_de,
  "es-ES": searchInputMessages_es,
  "fr-FR": searchInputMessages_fr,
  "pt-BR": searchInputMessages_pt,
});

/**
 * Available message keys for SearchInput component
 */
export type SearchInputMessageKey = "clearInput";
