/**
 * Pre-compiled de messages for ComboBox
 * Generated by @internationalized/string-compiler
 * DO NOT EDIT MANUALLY
 */

export default {
  clearSelection: `Auswahl löschen`,
  comboboxDialog: `Combobox-Dialog`,
  filterOptions: `Combobox-Optionen filtern`,
  options: `Combobox-Optionen`,
  selectedValues: `Ausgewählte Werte`,
  toggleCombobox: `Combobox umschalten`,
};
