/**
 * Pre-compiled en messages for ComboBox
 * Generated by @internationalized/string-compiler
 * DO NOT EDIT MANUALLY
 */

export default {
  clearSelection: `Clear selection`,
  comboboxDialog: `Combobox dialog`,
  filterOptions: `Filter combobox options`,
  options: `Combobox options`,
  selectedValues: `Selected values`,
  toggleCombobox: `Toggle combobox`,
};
