/**
 * Pre-compiled es messages for ComboBox
 * Generated by @internationalized/string-compiler
 * DO NOT EDIT MANUALLY
 */

export default {
  clearSelection: `Borrar selección`,
  comboboxDialog: `Diálogo Combobox`,
  filterOptions: `Filtrar opciones Combobox`,
  options: `Opciones Combobox`,
  selectedValues: `Valores seleccionados`,
  toggleCombobox: `Conmutar combobox`,
};
